<?php echo View::content()?>

<h4 class="center-align"> CREANDO NUEVA SECCION</h4>
<div class="container">

<?php echo Form::open() ;?>
    <div class="section">
        <div class="row">
            <!-- NOMBRE CATEGORIA -->
            <div class="input-field col s12">
                <i class="material-icons prefix">account_circle</i>
                <label for="Cargo">Seccion:
                    <?= Form::text('secciones.nombre_seccion'); ?></label>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="row">
            <!-- HABILITADO -->
            <div class="input-field col s12">
                <i class="material-icons prefix">account_circle</i>
                <label for="habilitado">Habilitado:</label><br>
                    <?php
                    $arreglo = array('Inhabilitado', 'Habilitado');
                    echo Form::select('secciones.habilitado', $arreglo);
                    ?>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="row">
            <div class="input-field col s12 center-align">
                <?php echo Form::submit('Enviar',"class='btn green'"); ?>
                <?php echo Html::linkAction('index', 'Regresar', "class='btn green darken-1'") ?>
            </div>
        </div>
    </div>
    <?php echo Form::close(); ?>
</div>