<div class="row section">

    <?php View::content(); ?>
    <h3 class="center"><b>Formulario de registro Profesores</b></h3>

    <?php echo Form::open(); ?>

    <div class="col s6">
        <label for="">Ingrese el primer nombre
            <?php echo Form::text('profesores.primer_nombre_profesor'); ?>
        </label>
    </div>

    <div class="col s6">
        <label for="nombre2">Ingrese el segundo nombre
            <?php echo  Form::text('profesores.segundo_nombre_profesor '); ?>
        </label>
    </div>

    <div class="col s6">
        <label for="">Ingrese el primer apellido
            <?php echo Form::text('profesores.primer_apellido_profesor'); ?>
        </label>
    </div>

    <div class="col s6">
        <label for="">Ingrese el segundo apellido
            <?php echo Form::text('profesores.segundo_apellido_profesor'); ?>
        </label>
    </div>

    <div class="col s6">
        <label for="">Ingrese el DUI
            <?php echo Form::text('profesores.dui'); ?>
        </label>
    </div>

    <div class="col s6">
        <label for="">Ingrese el NIP
            <?php echo Form::text('profesores.nip'); ?>
        </label>
    </div>

    <div class="col s6">
        <label for="">Ingrese el NIT
            <?php echo Form::text('profesores.nit'); ?>
        </label>
    </div>

    <div class="col s12">
        <?php echo Form::submit('Guardar', 'class="btn blue"') ?>
        <?php echo Form::reset('Limpiar', 'class="btn blue"') ?>
    </div>

    <?php echo Form::close(); ?>

</div>