<div class="row">
    <?php View::content() ?>
    <!-- <h3 class="center-align">Ministerio De Educacion</h3> -->
    <h3 class="center-align">Instituto Nacional De Sonzacate</h3>
    <h4 class="center-align">Registro de profesores <?php echo date('Y'); ?></h4>
</div>


<?php echo Form::open(); ?>

<div class="section">
    <div class="row">
        <!-- PRIMER NOMBRE -->
        <div class="input-field col s6">
            <i class="material-icons prefix">account_circle</i>
            <label for="Primer_nombre">Primer Nombre:
                <?= Form::text('profesores.primer_nombre_profesor'); ?></label>
        </div>

        <!-- SEGUNDO NOMBRE -->
        <div class="input-field col s6">
            <i class="material-icons prefix">account_circle</i>
            <label for="Primer_nombre">Segundo Nombre:
                <?= Form::text('profesores.segundo_nombre_profesor'); ?></label>
        </div>
    </div>
</div>

<div class="section">
    <div class="row">
        <!-- PRIMER APELLIDO -->
        <div class="input-field col s6">
            <i class="material-icons prefix">account_circle</i>
            <label for="Primer_nombre">Primer Apellido:
                <?= Form::text('profesores.primer_apellido_profesor'); ?></label>
        </div>

        <!-- SEGUNDO APELLIDO -->
        <div class="input-field col s6">
            <i class="material-icons prefix">account_circle</i>
            <label for="Primer_nombre">Segundo Apellido:
                <?= Form::text('profesores.segundo_apellido_profesor'); ?></label>
        </div>
    </div>
</div>

<div class="section">
    <div class="row">
        <!-- DUI -->
        <div class="input-field col s6">
            <i class="material-icons prefix">featured_play_list</i>
            <label for="Primer_nombre">DUI:
                <?= Form::text('profesores.dui'); ?></label>
        </div>

        <!-- NIP -->
        <div class="input-field col s6">
            <i class="material-icons prefix">featured_play_list</i>
            <label for="Primer_nombre">NIP:
                <?= Form::text('profesores.nip'); ?></label>
        </div>
    </div>
</div>

<div class="section">
    <div class="row">
        <!-- NIT -->
        <div class="input-field col s6">
            <i class="material-icons prefix">event_note</i>
            <label for="Primer_nombre">NIT:
                <?= Form::text('profesores.nit'); ?></label>
        </div>

        <!-- HABILITADO -->
        <div class="input-field col s6">
            <i class="material-icons prefix">content_copy</i>
            <label for="habilitado">Habilitado:</label><br>
                <?php
                $arreglo = array('Inhabilitado', 'Habilitado');
                echo Form::select('profesores.habilitado', $arreglo);
                ?>
        </div>
    </div>
</div>

<div class="section">
    <div class="row">
        <div class="input-field col s12 center-align">
            <?php echo Form::hidden('profesores.id'); ?>
            <button class="btn waves-effect waves-light " type="submit" name="action">Enviar
            <i class="material-icons right">send</i>
            </button>
        </div> 
    </div>
</div>

<?php echo Form::close(); ?>