<div class="row">
    <?php View::content() ?>
    <h3 class="center-align">Registro de profesores <?php echo date('Y'); ?></h3>
    <h4 class="center-align">(I.N.S.O)</h4>
</div>


<?php echo Form::open(); ?>

<div class="section">
    <div class="row">
        <!-- PRIMER NOMBRE -->
        <div class="input-field col s6">
            <i class="material-icons prefix">account_circle</i>
            <label for="Primer_nombre">Primer Nombre:
                <?= Form::text('profesores.primer_nombre_profesor'); ?></label>
        </div>

        <!-- SEGUNDO NOMBRE -->
        <div class="input-field col s6">
            <i class="material-icons prefix">account_circle</i>
            <label for="Primer_nombre">Segundo Nombre:
                <?= Form::text('profesores.segundo_nombre_profesor'); ?></label>
        </div>
    </div>
</div>

<div class="section">
    <div class="row">
        <!-- PRIMER APELLIDO -->
        <div class="input-field col s6">
            <i class="material-icons prefix">account_circle</i>
            <label for="Primer_nombre">Primer Apellido:
                <?= Form::text('profesores.primer_apellido_profesor'); ?></label>
        </div>

        <!-- SEGUNDO APELLIDO -->
        <div class="input-field col s6">
            <i class="material-icons prefix">account_circle</i>
            <label for="Primer_nombre">Segundo Apellido:
                <?= Form::text('profesores.segundo_apellido_profesor'); ?></label>
        </div>
    </div>
</div>

<div class="section">
    <div class="row">
        <!-- DUI -->
        <div class="input-field col s12">
            <i class="material-icons prefix">content_paste</i>
            <label for="direccion">Direccion:
                <?= Form::text('profesores.direccion'); ?></label>
        </div>
    </div>
</div>

<div class="section">
    <div class="row">
        <!-- DUI -->
        <div class="input-field col s6">
            <i class="material-icons prefix">assignment</i>
            <label for="dui">DUI:
                <?= Form::text('profesores.dui'); ?></label>
        </div>

        <!-- NIP -->
        <div class="input-field col s6">
            <i class="material-icons prefix">assignment</i>
            <label for="nip">NIP:
                <?= Form::text('profesores.nip'); ?></label>
        </div>
    </div>
</div>

<div class="section">
    <div class="row">
        <!-- NIT -->
        <div class="input-field col s6">
            <i class="material-icons prefix">assignment</i>
            <label for="nit">NIT:
                <?= Form::text('profesores.nit'); ?></label>
        </div>

        <!-- NUP -->
        <div class="input-field col s6">
            <i class="material-icons prefix">assignment</i>
            <label for="nup">NUP:
                <?= Form::text('profesores.nup'); ?></label>
        </div>
        
    </div>
</div>

<div class="section">
    <div class="row">
        <!-- PARTIDA -->
        <div class="input-field col s6">
            <i class="material-icons prefix">content_paste</i>
            <label for="Partida">Partida:
                <?= Form::text('profesores.partida'); ?></label>
        </div>

        <!-- SUBNIVEL -->
        <div class="input-field col s6">
            <i class="material-icons prefix">content_paste</i>
            <label for="Subnivel">Subnivel:
                <?= Form::text('profesores.subnivel'); ?></label>
        </div>
    </div>
</div>

<div class="section">
    <div class="row">
            <!-- ESPECIALIZACION -->
        <div class="input-field col s4">
            <i class="material-icons prefix">date_range</i>
            <label for="Carrera_profesor">Especializacion:</label><br>
            <?php echo Form::dbSelect('profesores.carrera_id', 'nombre_carrera',  array('carreras', 'find')); ?>
        </div>

        <!-- CATEGORIAS -->
        <div class="input-field col s4">
            <i class="material-icons prefix">date_range</i>
            <label for="Categoria_profesor">Categoria:</label><br>
            <?php echo Form::dbSelect('profesores.categoria_id', 'nombre_categoria',  array('categorias', 'find')); ?>
        </div>

        <!-- CARGOS -->
        <div class="input-field col s4">
            <i class="material-icons prefix">date_range</i>
            <label for="Cargo_profesor">Cargo:</label><br>
            <?php echo Form::dbSelect('profesores.cargo_id', 'nombre_cargo',  array('cargos', 'find')); ?>
        </div>
    </div>
</div>

<div class="section">
    <div class="row">
        <!-- PARTIDA -->
        <div class="input-field col s6">
            <i class="material-icons prefix">insert_invitation</i>
            <label for="Partida">Fecha de ingreso:
                <?= Form::date('profesores.fecha_ingreso'); ?></label>
        </div>

        <!-- SUBNIVEL -->
        <div class="input-field col s6">
            <i class="material-icons prefix">lock_open</i>
            <label for="Seccion">Habilitado:</label><br>
                <?php
                    $habilitado = array('Inhabilitado', 'Habilitado');
                    echo Form::select('profesores.habilitado',$habilitado);
                ?>
        </div>
    </div>
</div>


<div class="section">
    <div class="row">
        <div class="input-field col s12 center-align">
        <?php echo Form::hidden('profesores.id'); ?>
            <button class="btn waves-effect waves-light " type="submit" name="action">Actualizar
            <i class="material-icons right">send</i>
            </button>
            <?php echo Html::linkAction('index', 'regresar', "class='btn green darken-1'") ?>
        </div> 
    </div>
</div>

<?php echo Form::close(); ?>