<?php echo View::content() ?>
<h3 class="center">Registro de profesores</h3>

<?php echo Html::linkAction('create', 'Nuevo Profesor +', "class='btn green right'")  ?>

<table class="centered table striped">
    <tr>
        <thead class="blue lighten-4 ">
            <th>ID</th>
            <th>PROFESOR/A</th>
            <th>DUI</th>
            <th>NIP</th>
            <th>NIT</th>
            <th>HABILITADO</th>
            <th>ACCIONES</th>
        </thead>

        <?php foreach ($ListaProfesores->items as $item) :  ?>
            <tr>
                <td><?= $item->id ?></td>
                <td><?= $item->primer_nombre_profesor?> <?=$item->segundo_nombre_profesor ?> <?= $item->primer_apellido_profesor?> <?= $item->segundo_apellido_profesor?></td>
                <td><?= $item->dui ?></td>
                <td><?= $item->nip ?></td>
                <td><?= $item->nit ?></td>
                <td>
                    <?php
                    if ($item->habilitado == 0) {
                        echo "Inhabilitado";
                    }
                    if ($item->habilitado == 1) {
                        echo "Habilitado";
                    }
                    ?>
                </td>
                <td>
                    <?php echo Html::linkAction("edit/$item->id/", "Editar", 'class="btn"') ?>
                    <?php echo Html::linkAction("del/$item->id/", "Borrar", 'class="btn red"') ?>
                        </td>
            </tr>
        <?php endforeach ?>
    </tr>
</table>

