<?php echo View::content() ?>
<h3 class="center"><b>Registro de profesores</b></h3>

<table class="centered">
    <tr>
        <thead class="blue lighten-4 ">
            <th>Id</th>
            <th>Primer nombre</th>
            <th>Segundo nombre</th>
            <th>Primer apellido</th>
            <th>Segundo apellido</th>
            <th>DUI</th>
            <th>NIP</th>
            <th>NIT</th>
            <th>Acciones</th>
        </thead>

        <?php foreach ($ListaProfesores->items as $item) :  ?>
    <tr class="blue lighten-4 ">
        <td><?php echo $item->id ?></td>
        <td><?php echo $item->primer_nombre ?></td>
        <td><?php echo $item->segundo_nombre ?></td>
        <td><?php echo $item->primer_apellido ?></td>
        <td><?php echo $item->segundo_apellido ?></td>
        <td><?php echo $item->dui ?></td>
        <td><?php echo $item->nip ?></td>
        <td><?php echo $item->nit ?></td>
        <td>
            <?php echo Html::linkAction("edit/$item->id/", "Editar", 'class="btn"') ?>
            <?php echo Html::linkAction("del/$item->id/", "Borrar", 'class="btn red"') ?>
        </td>
    </tr>
    </tr>
<?php endforeach;  ?>
</tr>
</table>