<div class="row section">

    <?php View::content(); ?>
    <h3 class="center"><b>Centros Escolares</b></h3>

    <?php echo Form::open(); ?>

    <div class="col s6">
        <label for="">Nombre Centro escolar
            <?php echo Form::text('centroescolares.nombre_centroescolar'); ?>
        </label>
    </div>

    <div class="col s6">
        <label for="">Codigo Infraestructura
            <?php echo  Form::text('centroescolares.codigo_infraestructura'); ?>
        </label>
    </div>

    <div class="col s6">
        <label for="habilitado">Habilitado
            <?php
            $arreglo = array('Inhabilitado', 'Habilitado');
            echo Form::select('centroescolares.habilitado', $arreglo);
            ?>
        </label>
    </div>


    <div class="col s12">
        <?php echo Form::submit('Guardar', 'class="btn green"') ?>
        <?php echo Form::reset('Limpiar', 'class="btn blue"') ?>
        <?php echo Html::linkAction('index', 'regresar', "class='btn red darken-1'") ?>
    </div>

    <?php echo Form::close(); ?>

</div>