<?php echo View::content() ?>
<h4 class="center">LISTA DE CENTROS ESCOLARES</h4>

<?php echo Html::linkAction('create', 'Nuevo centro escolar +', "class='btn green accent-4'")  ?>

<br>
<hr>

<table class="responsive-table centered table striped">

    <tr>
            <thead class="blue lighten-4">
                <th>id</th>
                <th>CENTRO ESCOLAR</th>
                <th>CODIGO INFRAESTRUCTURA</th>
                <th>ACTIVO</th>
                <th>ACCIONES</th>
            </thead>

        <?php foreach ($ListaCentroescolares->items as $item) : ?>
            <tr>
                <td><?php echo $item->id ?></td>
                <td><?php echo $item->nombre_centroescolar ?></td>
                <td><?php echo $item->codigo_infraestructura ?></td>
                <td>
                    <?php
                    if ($item->habilitado == 1) {
                        echo "Habilitado";
                    }
                    if ($item->habilitado == 0) {
                        echo "Inhabilitado";
                    }
                    ?>
                </td>
                <td>
                    <?php echo Html::linkAction("edit/$item->id/", "Editar", 'class="btn blue darken-3"') ?>
                    <?php echo Html::linkAction("del/$item->id/", "Borrar", 'class="btn red"') ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tr>

</table>


