
<?php echo View::content() ?>

<h3 class="center">
    Categoria de profesores
</h3>
<?php echo Html::linkAction("create", 'Agregar Categoria +', "class='btn green accent-4'") ?>

<table class="responsive-table centered table striped">
    <thead class="blue lighten-4">
        <th>ID</th>
        <th>NOMBRE CATEGORIA</th>
        <th>HABILITADO</th>
        <th>ACCIONES</th>
    </thead>
    <?php foreach($listaCategorias->items as $item) :?>
            <tr>
                <td><?php echo $item->id ?></td>
                <td><?php echo $item->nombre_categoria ?></td>
                <td>
                    <?php 
                        if ($item->habilitado == 1) {
                            echo "Habilitado";
                        }
                        if ($item->habilitado == 0) {
                            echo "Inhabilitado";
                        }
                    ?>
                </td>
                <td>
                    <?php echo Html::linkAction('edit/'.$item->id,'Editar',"class='btn blue darken-3'")  ?>
                    <?php echo Html::linkAction('del/'.$item->id,'Eliminar', "class='btn red'") ?><br/>
                </td>
            </tr>
        <?php endforeach; ?>
</table>
        
<?php if($listaCategorias->prev) echo Html::linkAction("index/$listaCategorias->prev", '<< Anterior|') ?>
<?php if($listaCategorias->next) echo Html::linkAction("index/$listaCategorias->next/", 'Próximo >>') ?>

    
