<!-- CODIGO FUNCIONANDO -->
<?php echo View::content(); ?>
<?php echo Tag::js('jsbarcode'); ?>
<h4 class="center-align">IMPRESION DE CODIGO DE BARRA POR CADA ESTUDIANTE.</h4>
    <div class="row">
        <div class="input-field col s12 center-align">
            <?php echo Html::linkAction("pdf_barra", 'Generar Reporte En PDF', 'class="btn center-align"') ?>
        </div> 
    </div>


<!-- ___________________CONEXION A LA BASE DE DATOS_________________________ -->

<?php
    require 'conexion.php';
    $conexion = conexion();

    $especialidades = "SELECT nombre_especialidad FROM especialidades";
    ?>

<div class="row">
    <form method="post">
        <div class="col s5">
            <select name="especialidad">
                <option value="">BUSQUEDA SOLO POR ESPECIALIDAD</option>
                <?php 
                $especialidad = mysqli_query($conexion, $especialidades);
                while ($carrera = mysqli_fetch_assoc($especialidad)) {
                   echo '<option value="'.$carrera['nombre_especialidad'].'">'.$carrera['nombre_especialidad'].'</option>';
                }
                ?>
            </select>
        </div>
        <div class="col s3">
            <!-- <input type="text" name="nombre" placeholder="BUSQUEDA SOLO POR NOMBRE"> -->
            <select name="secciones">
                <option value="">BUSQUEDA SOLO POR SECCIONES</option>
                <option value="1">1° año</option>
                <option value="2">2° año</option>
                <option value="3">3° año</option>
            </select>
        </div>
        <div class="col s3">
            <input type="text" name="anio" placeholder="BUSQUEDA POR AÑO">
        </div>
        <div class="col s1">
            <button type="submit" class="btn green" name="Buscar">Buscar</button>
        </div>
    </form>

    <?php echo View::content() ?>

    
    <table class="centered striped responsive-table">
        <tr>
            <thead class="blue lighten-4 ">
                <th>ID</th>
                <th>NIE</th>
                <th>ALUMNO/A</th>
                <th>ESPECIALIDAD</th>
                <th>GRADO</th>
                <th>AÑO</th>
                <th>CODIGO</th>
            </thead>

            <?php
                $arraycodigos = array();
                foreach ($matriculas as $item) :?>
                <?php $arraycodigos[] = (String)$item->nie; ?>
        <tr>
        <td><?= $item->id?></td>
            <td><?= $item->nie?></td>
            <td><?= $item->primer_nombre ?> <?= $item->segundo_nombre ?> <?= $item->primer_apellido ?> <?= $item->segundo_apellido ?></td>
            <td ><?= $item->nombre_especialidad?></td>
            <td><?php
                if ($item->id_seccion == 1) {
                    echo '1° Año';
                }
                if ($item->id_seccion == 2) {
                    echo '2° Año';
                } 
                if ($item->id_seccion == 3) {
                    echo '3° Año';
                }
            ?></td>
            </td>
            <td><?= $item->anio?></td>
            <td>
                <svg id="<?php echo "barcode".$item->nie?>"></svg>
            </td>
            
        </tr>
<?php
    endforeach;
?>
</tr>
    </table>
</div>