<?php echo View::content() ?>

<h4 class="center-align">COMPROBANTE DE MATRICULA.</h4>

<form action="" method="post">
    <div class="row">
        <div class="input-field col s6">
        <i class="material-icons prefix">event</i>
            <label for="nombres">Nombre del alumno:
                <input type="text" name="nombres"></label>
        </div>

        <div class="input-field col s6">
            <i class="material-icons prefix">edit</i>
            <label for="Estudio-parvularia">Año:</label><br>
        <?php $año = array('1'=>'1° Año','2'=>'2° Año', '3'=>'3° Año'); echo Form::Select('anio', $año); ?>
        </div>
    </div>
    <div class="row">
        <div class="col s12 center-align">   
            <?php echo Form::submit('Generar Comprobante',"class='btn green'"); ?>
        </div>
    </div>
</form>

<table class="responsive-table centered table striped">
    <thead class="light-blue lighten-1">
        <th>ID</th>
        <th>NOMBRES</th>
        <th>APELLIDOS</th>
        <th>ESPECIALIDAD</th>
        <th>GRADO</th>
        <th>SECCION</th>
        <th>AÑO</th>
    </thead>
    <?php foreach ($comprobante as $item) : ?>
        <tr>
            <td><?= $item->id ?></td>
            <td><?= $item->getAlumnos()->primer_nombre?> <?= $item->getAlumnos()->segundo_nombre?></td>
            <td><?= $item->getAlumnos()->primer_apellido?> <?= $item->getAlumnos()->segundo_apellido?></td>
            <td><?= $item->getEspecialidades()->nombre_especialidad?></td>
        </tr>
    <?php endforeach; ?>
</table>