<div class="row section">

    <?php echo View::content(); ?>
    <?php echo Tag::js('jquery'); ?>
    <h3 class="center"><b>Matriculas</b></h3>

    <div class="row section">
        <div class="col s6">
            <label for="nombre">Nombre del estudiante a buscar.
                <?php echo Form::text('nombre'); ?>
            </label>
        </div>
        <div class="col s12">
            <div class="" id="resultado">
            </div>
        </div>
    </div>

    <?php echo Form::open(); ?>

    <div class="col s6">
        <label for="">Nombre del estudiante
            <?php echo Form::text('matriculas.id_alumnos'); ?>
        </label>
    </div>
    <div class="col s6">
        <label for="">Ingrese la especialidad
            <?php 
            $especialidades = array('Seleccionar','Técnico vocacional en desarrollo de software'=> 'Técnico vocacional en desarrollo de software','Atención primaria en salud'=> 'Atención primaria en salud','Administrativo contable'=> 'Administrativo contable','Mecánica automotriz'=> 'Mecánica automotriz','General'=>'General');
            echo Form::select('matriculas.id_especialidad', $especialidades); ?>
        </label>
    </div>
    <div class="col s6">
        <label for="">Ingrese la seccion
            <?php
            $seccion = array('Seleccionar','1° "A"'=>'1° "A"', '1° "B"' => '1° "B"', '1° "C"' => '1° "C"', '2° "A"' => '2° "A"', '2° "B"' => '2° "B"', '2° "C"' => '2° "C"', '3° "A"' => '3° "A"', '3° "B"' => '3° "B"'); 
            echo Form::select('matriculas.id_seccion',$seccion); ?>
        </label>
    </div>

    <div class="col s6">
        <label for="">Ingrese el Año
            <?php echo Form::text('matriculas.anio'); ?>
        </label>
    </div>

    <div class="col s6">
        <label for="egresado">Egresado
            <?php
            $arreglo = array('No', 'Si');
            echo Form::select('matriculas.egresado', $arreglo);
            ?>
        </label>
    </div>

    <div class="col s6">
        <label for="habilitado">Habilitado
            <?php
            $arreglo = array('Inhabilitado', 'Habilitado');
            echo Form::select('matriculas.habilitado', $arreglo);
            ?>
        </label>
    </div>


    <div class="col s12">
        <?php echo Form::submit('Guardar', 'class="btn green"') ?>
        <?php echo Form::reset('Limpiar', 'class="btn blue"') ?>
        <?php echo Html::linkAction('index', 'regresar', "class='btn red darken-1'") ?>
    </div>

    <?php echo Form::close(); ?>
    <?php $arreglo = (array)$Alumnado ;?>
</div>
<script>
    const buscado = querySelector('#nombre');
    buscado.keyUp(fucntion(){
        console.log('presionando');
    })
    var listado = <?php echo json_encode($Alumnado);?>;
    console.log(listado.items[0].primer_nombre);
</script>
