<?php echo View::content() ?>
<h3 class="center"><b>Registro de matriculas</b></h3>

<table class="centered">
    <tr>
        <thead class="blue">
            <th>Id</th>
            <th>Alumno</th>
            <th>Especialidad</th>
            <th>Seccion</th>
            <th>Año</th>
            <th>Estado</th>
            <th>Egresado</th>
            <th>Acciones</th>
        </thead>

        <?php foreach ($ListaMatriculas->items as $item) :  ?>
    <tr>
        <td><?php echo $item->id_matriculas ?></td>
        <td><?php echo Form::dbSelect('alumnos.nombre_alumno');?></td>
        <td><?php echo $item->especialidad_id?></td>
        <td><?php echo $item->id_seccion ?></td>
        <td><?php echo $item->anio ?></td>
        <td><?php echo $item->estado ?></td>
        <td><?php echo $item->egresado ?></td>
        <td>
            <?php echo Html::linkAction("edit/$item->id/", "Editar", 'class="btn"') ?>
            <?php echo Html::linkAction("del/$item->id/", "Borrar", 'class="btn red"') ?>
        </td>
    </tr>
    </tr>
<?php endforeach;  ?>
</tr>
</table>