<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <div class="">
        <h2>Buscador</h2>

        <form action="" method="post">
            <div class="row">
                <div class="col s10">
                    <input type="text" name="Buscar" class="form-control" placeholder="Buscar" autocomplete="off">
                </div>

                <div class="col s2">
                    <button type="submit" class="btn green">Buscar</button>
                </div>
            </div>

        </form>

        <?php
        require 'conexion.php';
        $conexion = conexion();

        if (!empty($_POST['Buscar'])) {
            $Buscar = $_POST['Buscar'];
            $sql = "SELECT id, nie, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, id_especialidad_ingreso, anio_bachillerato FROM alumnos WHERE nie LIKE '%$Buscar%'";
        } else {
            $sql = "SELECT id, nie, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido, id_especialidad_ingreso, anio_bachillerato FROM alumnos";
        }



        ?>


        <?php echo View::content() ?>

        <?php echo Html::linkAction('create', 'Nueva matricula +', "class='btn green right'")  ?>
        <table class="centered striped responsive-table">
            <tr>
                <thead class="blue lighten-4 ">
                    <th>Id</th>
                    <th>NIE</th>
                    <th>Alumno</th>
                    <th>Especialidad</th>
                    <th>Seccion</th>
                    <th>Año</th>
                    <th>Egresado</th>
                    <th>Estado</th>
                    <th>Habilitado</th>
                    <th>Acciones</th>
                </thead>
                <?php
                $query = mysqli_query($conexion, $sql);
                if ($query) {
                    while ($data = mysqli_fetch_assoc($query)) {

                ?>

                <tr>
                    <td><?php echo $data['id'] ?></td>
                    <td><?php echo $data['nie'] ?></td>
                    <td><?php echo $data['primer_nombre'] . ' ' . $data['segundo_nombre'] . ' ' . $data['primer_apellido'] . ' ' . $data['segundo_apellido'] ?></td>
                    <td><?php
                            if ($data['id_especialidad_ingreso'] == 1) {
                                echo "Técnico vocacional en desarrollo de software";
                            }
                            if ($data['id_especialidad_ingreso'] == 2) {
                                echo "Administrativo contable";
                            }
                            if ($data['id_especialidad_ingreso'] == 3) {
                                echo "Atención primaria en salud";
                            }
                            if ($data['id_especialidad_ingreso'] == 4) {
                                echo "Mecánica automotriz";
                            }
                            if ($data['id_especialidad_ingreso'] == 5) {
                                echo "General";
                            }
                        ?></td>
                    
                    <td><?php echo $data['anio_bachillerato'] ?></td>
                    <td><?php echo $data['anio_bachillerato'] ?></td>
                    <td><?php echo $data['anio_bachillerato'] ?></td>
                    <td><?php
                            if ($data['egresado'] == 1) {
                                echo "Si";
                            }
                            if ($data['egresado'] == 0) {
                                echo "No";
                            }
                        ?></td>
                    <td><?php
                            if ($data['habilitado'] == 1) {
                                echo "Habilitado";
                            }
                            if ($data['habilitado'] == 0) {
                                echo "Inhabilitado";
                            }
                        ?></td>


                    
                        <td>
                            <?php echo Html::linkAction("edit/$data[id]/", "Editar", 'class="btn"') ?>
                            <?php echo Html::linkAction("del/$data[id]/", "Borrar", 'class="btn red"') ?>
                        </td>
            <?php
                    }
                } else {
            ?>
            <td colspan="4">Busqueda sin resultados</td>
        <?php
                }
        ?>

            </tr>

            </tr>

        </table>
    </div>


</body>

</html>



<!-- <?php echo View::content() ?>
<h3 class="center"><b>Registro de matriculas</b></h3>


<?php echo Html::linkAction('create', 'Nueva matricula +', "class='btn green right'")  ?>

<table class="centered">
    <tr>
        <thead class="blue">
            <th>Id</th>
            <th>Alumno</th>
            <th>Especialidad</th>
            <th>Seccion</th>
            <th>Año</th>
            <th>Egresado</th>
            <th>Estado</th>
            <th>Acciones</th> 
        </thead>

        <?php foreach ($ListaMatriculas->items as $item) :  ?>
    <tr>
        <td><?php echo $item->id ?></td>
        <td><?php echo $item->id_alumnos ?></td>
        <td><?php echo $item->id_especialidad ?></td>
        <td><?php echo $item->id_seccion ?></td>
        <td><?php echo $item->anio ?></td>
        <td>
            <?php
            if ($item->egresado == 1) {
                echo "Si";
            }
            if ($item->egresado == 0) {
                echo "No";
            }
            ?>
        </td>
        <td>
            <?php
            if ($item->habilitado == 1) {
                echo "Habilitado";
            }
            if ($item->habilitado == 0) {
                echo "Inhabilitado";
            }
            ?>
        </td>
        <td>
            <?php echo Html::linkAction("edit/$item->id/", "Editar", 'class="btn"') ?>
            <?php echo Html::linkAction("del/$item->id/", "Borrar", 'class="btn red"') ?>
        </td>
    </tr>
    </tr>
<?php endforeach;  ?>



 <?php foreach ($ListaMatriculas->items as $item) :  ?>
                                <td><?php echo Html::linkAction("edit/$item->id/", "Editar", 'class="btn"') ?>
                                    <?php echo Html::linkAction("del/$item->id/", "Borrar", 'class="btn red"') ?></td>
                            <?php endforeach;  ?>
</tr>
</table> -->