
<!-- CODIGO FUNCIONANDO -->
<?php echo View::content(); ?>
<?php echo Tag::js('jsbarcode'); ?>

<?php

    require 'conexion.php';
    $conexion = conexion();

    $sql = "SELECT matriculas.id, matriculas.id_seccion, matriculas.anio, alumnos.nie, alumnos.primer_nombre, alumnos.segundo_nombre, alumnos.primer_apellido, alumnos.segundo_apellido, especialidades.nombre_especialidad FROM matriculas, alumnos, especialidades WHERE matriculas.id_alumnos=alumnos.id AND matriculas.id_especialidad=especialidades.id";

    if (isset($_POST['Buscar'])) {
        // BUSCA CUANDO SECCION Y ANIO VAN LLENOS
        if (empty($_POST['especialidad'])) {
            $Buscar_anio = $_POST['anio'];
            $Buscar_seccion = $_POST['secciones'];
            $sql = "SELECT matriculas.id, matriculas.id_seccion, matriculas.anio, alumnos.nie, alumnos.primer_nombre, alumnos.segundo_nombre, alumnos.primer_apellido, alumnos.segundo_apellido, especialidades.nombre_especialidad FROM matriculas, alumnos, especialidades WHERE id_seccion LIKE $Buscar_seccion AND anio LIKE '$Buscar_anio' AND matriculas.id_alumnos=alumnos.id AND matriculas.id_especialidad=especialidades.id";
            // BUSCA CUANDO ESPECIALIDAD Y ANIO VAN LLENOS
        } else if (empty($_POST['secciones'])){
            $Buscar_especialidad = $_POST['especialidad'];
            $Buscar_anio = $_POST['anio'];
            $sql = "SELECT matriculas.id, matriculas.id_seccion, matriculas.anio, alumnos.nie, alumnos.primer_nombre, alumnos.segundo_nombre, alumnos.primer_apellido, alumnos.segundo_apellido, especialidades.nombre_especialidad FROM matriculas, alumnos, especialidades WHERE nombre_especialidad LIKE '$Buscar_especialidad' AND anio LIKE '$Buscar_anio' AND matriculas.id_alumnos=alumnos.id AND matriculas.id_especialidad=especialidades.id";
            // BUSCA CUANDO SECCION Y ESPECIALIDAD VAN LLENOS.
        }else if(empty($_POST['anio'])){
            $Buscar_seccion = $_POST['secciones'];
            $Buscar_especialidad = $_POST['especialidad'];
            $sql = "SELECT matriculas.id, matriculas.id_seccion, matriculas.anio, alumnos.nie, alumnos.primer_nombre, alumnos.segundo_nombre, alumnos.primer_apellido, alumnos.segundo_apellido, especialidades.nombre_especialidad FROM matriculas, alumnos, especialidades WHERE id_seccion LIKE $Buscar_seccion AND nombre_especialidad LIKE '$Buscar_especialidad' AND matriculas.id_alumnos=alumnos.id AND matriculas.id_especialidad=especialidades.id";
        } else{
            $Buscar_especialidad = $_POST['especialidad'];  
            $Buscar_seccion = $_POST['secciones'];
            $Buscar_anio = $_POST['anio'];
            $sql = "SELECT matriculas.id, matriculas.id_seccion, matriculas.anio, alumnos.nie, alumnos.primer_nombre, alumnos.segundo_nombre, alumnos.primer_apellido, alumnos.segundo_apellido, especialidades.nombre_especialidad FROM matriculas, alumnos, especialidades WHERE nombre_especialidad LIKE '$Buscar_especialidad' AND id_seccion LIKE $Buscar_seccion AND anio LIKE '$Buscar_anio' AND matriculas.id_alumnos=alumnos.id AND matriculas.id_especialidad=especialidades.id";
        }
    }

    ?>



    
    <table class="centered striped responsive-table">
        <tr>
            <thead class="blue lighten-4 ">
                <th>ID</th>
                <th>NIE</th>
                <th>ALUMNO/A</th>
                <th>ESPECIALIDAD</th>
                <th>GRADO</th>
                <th>AÑO</th>
                <th>CODIGO</th>
            </thead>

            <?php
            $query = mysqli_query($conexion, $sql);
            if ($query) {
                while ($data = mysqli_fetch_assoc($query)) {
            ?>
        <tr>
            <td><?php echo$data['id'] ?></td>
            <td><?php echo$data['nie'] ?></td>
            <td><?php echo $data['primer_nombre'] . ' ' . $data['segundo_nombre'] . ' ' . $data['primer_apellido'] . ' ' . $data['segundo_apellido'] ?></td>
            <td><?php echo$data['nombre_especialidad'] ?></td>
            <td>
                <?php 
                    if ($data['id_seccion'] == 1) {
                        echo '1° Año';
                    }
                    if ($data['id_seccion'] == 2) {
                        echo '2° Año';
                    }
                    if ($data['id_seccion'] == 3) {
                        echo '3° Año';
                    }
                ?>
            </td>
            <td><?php echo $data['anio']?></td>
            <td><img id="barcode" alt=""></td>
            <?php $codigo = $data['nie']; ?>
        </tr>

    <?php
                }
            } else {
    ?>
    <td colspan="4">Busqueda sin resultados</td>
<?php
            }
?>
</tr>
    </table>
</div>
<script>
    JsBarcode("#barcode", <?php echo $codigo;?>);
</script>