<?php echo View::content(); ?>
<h4 class="center-align">DATOS DE ESTUDIANTES POR SECCIONES</h4>

<form method="post" action="codigobarras" target="_blank">
    <div class="row">
        <div class="input-field col s5">
            <i class="material-icons prefix">assignment_ind</i>
            <label for="Especialidad">Especialidad:</label><br>
            <?php echo Form::dbSelect('especialidad', 'nombre_especialidad',  array('especialidades', 'find')); ?>
                
        </div>

        <div class="input-field col s4">
            <i class="material-icons prefix">edit</i>
            <select name="secciones">
                <option value="" disabled selected>Elija el año</option>
                <option value="1">1º Año</option>
                <option value="1">2º Año</option>
                <option value="3">3º Año</option>
              </select>
              <label>Año:</label>
        </div>

        <div class="input-field col s3">
            <i class="material-icons prefix">event</i>
            <label for="Año">Año:
                <?= Form::text('anio'); ?></label>
        </div>
    </div>
    <div class="row">
        <div class="col s12 center-align">   
            <?php echo Form::submit('Generar reporte',"class='btn green'"); ?>
        </div>
    </div>
</form>