<div class="row">
    <?php View::content() ?>
        <h3 class="center-align">REGISTRO DE MATRICULAS</h3>
</div>


<div class="row">
    <form method="post">
        <div class="input-field col s4">
            <input type="text" name="especialidad" placeholder="BUSQUEDA POR ESPECIALIDAD">
        </div>
        <div class="input-field col s4">
            <input type="text" name="seccion" placeholder="BUSQUEDA POR SECCION">
        </div>
        <div class="input-field col s4">
            <input type="text" name="anio" placeholder="BUSQUEDA POR AÑO">
        </div>
        <div class="input-field col s12 center-align">
            <button type="submit" class="btn green">Buscar</button>
        </div>
    </form>
</div>
