<div class="container">
   <?php View::content(); ?>     
   <div class="row">
      <?php echo form::open(); ?>
      <div class="cols6">
         <i class="material-icons prefix">account_circle</i>
         <label for="">Ingrese su nacionalidad 
         <?php echo Form::text('nacionalidades.nombre_nacionalidad') ?>
         </label>
      </div>
      <div class="col s6">
         <label for="habilitado">habilitado
            <?php
               $arreglo = array('Inhabilitado','Habilitado');
               echo Form::select('nacionalidades.habilitado', $arreglo);
            ?>
         </label>
      </div>
      <div class="col s12">
         <button class="btn waves-effect waves-light" type="submit" name="action">Enviar
         <i class="material-icons right">send</i>
      </button>
         <button class="btn waves-effect waves-light" type="reset" name="action">Limpiar
            <i class="material-icons right">send</i>
         </button>
      </div>   
      <?php echo Form::close(); ?>
   </div>
</div>