<div class="row">
   <?php View::content(); ?>
   <h3 class="center"><b>Nacionalidades</b></h3>

   <div class="section">
      <?php echo form::open(); ?>
      <div class="row">
         <div class="input-field col s6">
            <i class="material-icons prefix">account_circle</i>
            <label for="">Ingrese su nacionalidad 
            <?php echo Form::text('nacionalidades.nombre_nacionalidad') ?>
            </label>
         </div>
         <div class="input-field col s6">
            <select type=num name="habilitado">
               <option value="" disabled selected>elija su opcion</option>
               <option value="1">Habilitado</option>
               <option value="2">Desabilitado</option>
            </select>
            <label>Materialize Select</label>
         </div>
      </div>
  </div>

<div class="section">
   <div class="row">
      <div class="input-field col s12">
         <button class="btn waves-effect waves-light" type="submit" name="action">Enviar
         <i class="material-icons right">send</i>
      </button>
         <button class="btn waves-effect waves-light" type="reset" name="action">Limpiar
            <i class="material-icons right">send</i>
         </button>
      </div>   
   </div>
</div>
   
   <?php echo Form::close(); ?>
</div>