<?php echo View::content() ?>
<h3 class="center-align"><b>Nacionalidades</b></h3>
<table class="table striped">
    <thead>
        <th>ID</th>
        <th>NACIONALIDAD</th>
        <th>ACTIVO</th>
        <th>ACCIONES</th>
    </thead>
    <?php foreach($listaNacionalidades->items as $item): ?>
    <tr>
        <td><?php echo $item->id?></td>
        <td><?php echo $item->nombre_nacionalidad ?></td>
        <td>
            <?php 
                if ($item->habilitado == 1) {
                    echo "Habilitado";
                }
                if ($item->habilitado == 0) {
                    echo "Inhabilitado";
                }
            ?>
            </td>
           <td>
               <?php echo Html::linkAction('edit/'.$item->id, 'Editar', "class='btn'" ) ?>
               <?php echo Html::linkAction("del/$item->id/", 'Borrar', 'class="btn red"') ?>
           </td>
        </tr>
    <?php endforeach ?>
    <tr>
        <td><?php echo Html::linkAction('create','Nueva Nacionalidad', "class='btn green'") ?></td>
    </tr>


</table>
