<?php echo View::content() ?>
<h3 class="center"><b>Nacionalidades</b></h3>
<table class="centered">
   <tr>
      <thead class= "blue lighten-2">
         <th>Id</th>
         <th>Nacionalidad</th>
       </thead>

       <?php foreach($ListaNacionalidades->items as $item): ?>
           <tr>
               <td><?php echo $item->id?></td>
               <td><?php echo $item->nombre_nacionalidad ?></td>
              <td>
                  <?php echo Html::linkAction("edit/$item->id/", "Editar", 'class="btn"' ) ?>
                  <?php echo Html::linkAction("del/$item->id/", "Borrar", 'class="btn red"') ?>
              </td>
           </tr>
       <?php endforeach ?>
  </tr>
</table>