<?php echo View::content() ?>
<h4 class="center-align">NACIONALIDADES</h4>

<?php echo Html::linkAction('create','Nueva Nacionalidad', "class='btn green accent-4'") ?>

<br>
<hr>

<table class="responsive-table centered table striped">
    <thead class="blue lighten-4">
        <th>ID</th>
        <th>NACIONALIDAD</th>
        <th>ACTIVO</th>
        <th>ACCIONES</th>
    </thead>
    <?php foreach($listaNacionalidades->items as $item): ?>
    <tr>
        <td><?php echo $item->id?></td>
        <td><?php echo $item->nombre_nacionalidad ?></td>
        <td>
            <?php 
                if ($item->habilitado == 1) {
                    echo "Habilitado";
                }
                if ($item->habilitado == 0) {
                    echo "Inhabilitado";
                }
            ?>
            </td>
           <td>
               <?php echo Html::linkAction('edit/'.$item->id, 'Editar', "class='btn blue darken-3'" ) ?>
               <?php echo Html::linkAction("del/$item->id/", 'Borrar', 'class="btn red"') ?>
           </td>
        </tr>
    <?php endforeach ?>
</table>