<?php echo View::content() ?>
<h3 class="center"><b>Centros escolares</b></h3>

<table class="centered">
    <tr>
        <thead>
            <th>id</th>
            <th>Centro escolar</th>
            <th>Codigo infraestructura</th>
            <th>Acciones</th>
        </thead>

        <?php foreach ($ListaCentros_escolares->items as $item) : ?>
    <tr>
        <td><?php echo $item->id ?></td>
        <td><?php echo $item->nombre_centroescolar ?></td>
        <td><?php echo $item->codigo_infraestructura ?></td>
        <td>
        <?php echo Html::linkAction("edit/$item->id/", "Editar", 'class="btn"') ?>
        <?php echo Html::linkAction("del/$item->id/", "Borrar", 'class="btn red"') ?></td>
    </tr>
<?php endforeach ?>
</tr>
</table>