<div class="row">
    <?php View::content(); ?>
    <h3 class="center">canton</h3>
    <?php echo Form::open(); ?>
        <div class="row">
            <div class="col s6">
                <label for="">nombre del canton
                <?php echo Form::text('cantones.nombre_canton'); ?>
                </label>
            </div>

            <div class="col s6">
                <label for="habilitado">Habilitado
                <?php 
                $arreglo = array('Inhabilitado','Habilitado');
                echo Form::select('cantones.habilitado', $arreglo);
                 ?>
            
                </label>
            </div>
        </div>
        <div class="col s12">
            <?php echo Form::submit('Guardar',"class='btn teal'"); ?>
        </div>
    <?php echo Form::close(); ?>
</div>

