<div class="row">
    <?php View::content(); ?>
    <h3>canton</h3>
    <?php echo Form::open(); ?>
        <div class="row">
            <div class="col s6">
            <label for="">
            <?php echo Form::text('cantones.nombre_canton'); ?>
            </label>
            </div>
            <div class="col s6">
            <label for="">
                <input type="checkbox">
                <?php echo Form::check('cantones.habilitado','1','',true); ?>
                <span>Habilitado</span>
            </label>
            </div>
        </div>
        <div class="col s12">
            <?php echo Form::submit('Guardar',"class='btn teal'"); ?>
        </div>
    <?php echo Form::close(); ?>
</div>

