<div class="row">
    <?php View::content(); ?>
    <h3>canton</h3>
    <?phpForm::open(); ?>
        <div class="row">
            <div class="col s6">
            <label for="Nombre_canton">
            <?php Form::text('Cantones.nombre_canton'); ?></label>
            </div>
        </div>
        <div class="col s12">
            <?php Form::submit('guardar',"class='btn teal'"); ?>
        </div>
    <?= Form::close(); ?>
</div>