<div class="row">
    <?php echo View::content(); ?>
    <?php echo Form::open(); ?>
        <div class="col s6">
            <label >
            <?php echo Form::text('cantones.nombre_canton'); ?></label>
        </div>
        <div class="col s6">
            <label>
                <input type="checkbox"/>
                <?php echo Form::check('cantones.habilitado','1','',true); ?>
                <span>habilitado</span>
            </label>
        </div>
        <div class="col s12">
            <?php echo Form::hidden('cantones.id');?>
            <?php echo Form::submit('guardar','class="btn teal"'); ?>
        </div>
    <?php echo Form::close(); ?>
</div>