<?php echo View::content();?>
    <h3 class="centered">Cantones</h3>

<?php echo Html::linkAction('create', 'Nuevo Canton',"class='btn green right'") ?>

<table class="centered table striped">
    <tr>
        <thead class="blue lighten-3">  
            <th>Id</th>
            <th>Canton</th>
            <th>Activo</th>
            <th>Acciones</th>
        </thead>
        <?php foreach ($listaCantones->items as $item): ?> 
            <tr>
                <td><?php echo $item->id?></td>
                <td><?php echo $item->nombre_canton?></td>
                <td>
                <?php 
                    if ($item->habilitado ==1){
                        echo "Habilitado";
                    }
                    if ($item->habilitado == 0){
                        echo "Inhabilitado";
                    }
                    ?>
                </td>
                <td>
                    <?php echo Html::LinkAction("edit/$item->id",'editar','class="btn"')?>
                    <?php echo Html::LinkAction("del/$item->id",'borrar','class="btn red"')?>
                </td>
            </tr>
        <?php endforeach ?>
    </tr>
</table>