<?php echo View::content();?>
<div class="center">
    <h3 class="card panel light-blue darken-4">Cantones</h3>
</div>
<table>
<thead class="blue lighten-3">
    <th>id</th>
    <th>nombre_canton</th>
    <th>acciones</th>
</thead>
    <?php foreach ($listaCantones->items as $item): ?> 
        <tr>
            <td><?php echo $item->id?></td>
            <td><?php echo $item->nombre_canton?></td>
            <td>
                <?php echo Html::LinkAction("edit/$item->id",'editar','class="btn"')?>
                <?php echo Html::LinkAction("del/$item->id",'borrar','class="btn red"')?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>