<?php echo View::content();?>
<h3>Cantones</h3>
<table>
<thead>
    <th>id</th>
    <th>nombre_canton</th>
</thead>
    <?php foreach($listaCantones->items as $item): ?> 
        <tr>
            <td><?php echo $item->id_canton?></td>
            <td><?php echo $item->nombre_canton?></td>
            <td>
                <?php echo Html::LinkAction("edit/$item->id",'editar','class="btn"')?>
                <?php echo Html::LinkAction("del/$item->id",'borrar','class="btn red"')?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>