<div class="row section">

    <?php echo View::content(); ?>
    <h3 class="center"><b>Departamentos</b></h3>
    

    <?php echo Form::open(); ?>

    <div class="col s6">
        <label for="">Ingrese el departamento
            <?php echo Form::text('departamentos.nombre_departamento'); ?>
        </label>
    </div>

    <div class="col s6">
        <label for="habilitado">Habilitado
            <?php
            $arreglo = array('Inhabilitado', 'Habilitado');
            echo Form::select('centroescolares.habilitado', $arreglo);
            ?>
        </label>
    </div>

    <div class="col s12">
        <?php echo Form::submit('Guardar', 'class="btn blue"') ?>
        <?php echo Form::reset('Limpiar', 'class="btn blue"') ?>
        <?php echo Html::linkAction('index', 'regresar', "class='btn green'") ?>
    </div>

    <?php echo Form::close(); ?>

</div>