<?php echo View::content(); ?>
<?php echo Tag::js('jsbarcode'); ?>
<h3>Impresion de Codigos de Barra por Estudiante</h3>
<div class="row">
    <?php echo Form::open(); ?>
    <div class="col s12">
        <label for="codigo">Busqueda por codigo
            <input type="text" id="codigo"/>
        </label>
    </div>
    <div class="col s12">
        <img id="barcode" alt="">
    </div>
</div>
<script>
    JsBarcode("#barcode","ND0238011");
</script>