<?php echo View::content(); ?>
<?php echo Tag::js('jsbarcode'); ?>
<h3>Impresion de Codigos de Barra por Estudiante</h3>
<div class="row">
    <?php echo Form::open(); ?>
    <form action="" method="post">
        <div class="col s10">
            <label for="codigo">Busqueda por codigo
                <input type="text" name="Buscar_codigo" id="codigo" autocomplete="off" />
            </label>
        </div>
        <div class="col s2">
            <button type="submit" class="btn blue">Buscar</button>
        </div>

    </form>

    <?php
    require 'conexion.php';
    $conexion = conexion();

    if (!empty($_POST['Buscar_codigo'])) {
        $Buscar = $_POST['Buscar_codigo'];
        $sql = "SELECT id, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido FROM alumnos WHERE primer_nombre LIKE '%$Buscar%' OR segundo_nombre LIKE '%$Buscar%' OR primer_apellido LIKE '%$Buscar%' OR segundo_apellido LIKE '%$Buscar%'";
    } else {
        $sql = "SELECT id, primer_nombre, segundo_nombre, primer_apellido, segundo_apellido FROM alumnos";
    }
    ?>

    <?php echo View::content() ?>

    <table class="centerd striped responsive-table">
        <tr>
            <thead class="blue lighten-4 ">
                <th>Id</th>
                <th>Nombre</th>
                <th>Codigo</th>
            </thead>

            <?php
            $query = mysqli_query($conexion, $sql);
            if ($query) {
                while ($data = mysqli_fetch_assoc($query)) {

            ?>
        <tr>
            <td><?php echo $data['id'] ?></td>
            <td><?php echo $data['primer_nombre'] . ' ' . $data['segundo_nombre'] . ' ' . $data['primer_apellido'] . ' ' . $data['segundo_apellido'] ?></td>
            <td><img id="barcode" alt=""></td>
            <?php $codigo = $data['id']; ?>
        </tr>

    <?php
                }
            } else {
    ?>
    <td colspan="4">Busqueda sin resultados</td>
<?php
            }
?>
</tr>
    </table>



</div>
<script>
    JsBarcode("#barcode", <?php echo $codigo;?>);
</script>