<?php echo View::content() ?>

<h4 class="center-align">IDENTIFICACION DEL ESTUDIANTE.</h4>
<?php echo Html::linkAction("create", 'Agregar Alumno +', "class='btn'") ?>

<table class="responsive-table centered table striped">
    <thead class="light-blue lighten-1">
        <th>ID</th>
        <th>NOMBRES</th>
        <th>APELLIDOS</th>
        <th>NIE</th>
        <th>ESPECIALIDAD</th>
        <th>ACCIONES</th>
    </thead>
    <?php foreach ($listaAlumnos as $item) : ?>
        <tr>
            <td><?= $item->id ?></td>
            <td><?= $item->primer_nombre ?> <?= $item->segundo_nombre ?></td>
            <td><?= $item->primer_apellido ?> <?= $item->segundo_apellido ?></td>
            <td><?= $item->nie ?></td>
            <td><?= $item->getEspecialidades()->nombre_especialidad?></td>
            <td>
                <?php echo Html::linkAction("edit/$item->id/", 'Editar', 'class="btn "') ?>
                <?php echo Html::linkAction("pdf/$item->id/", 'Ficha', 'class="btn light-green accent-4"') ?>
                <?php echo Html::linkAction("del/$item->id/", 'Borrar', 'class="btn red"') ?>
            </td>
        </tr>

    <?php endforeach; ?>
</table>