<?php echo View::content() ?>

<h3 class="center">
    IDENTIFICACION DEL ESTUDIANTE
</h3>
<?php echo Html::linkAction("create", 'Agregar Alumno +', "class='btn'") ?>

<table class="responsive-table centered table striped">
    <thead class="blue lighten-3">
        <th>ID</th>
        <th>PRIMER NOMBRE</th>
        <th>SEGUNDO NOMBRE</th>
        <th>PRIMER APELLIDO</th>
        <th>SEGUNDO APELLIDO</th>
        <th>NIE</th>
        <th>ACCIONES</th>
    </thead>
    <?php foreach ($listaAlumnos->items as $item) : ?>
        <tr>
            <td><?php echo $item->id ?></td>
            <td><?php echo $item->primer_nombre ?></td>
            <td><?php echo $item->segundo_nombre ?></td>
            <td><?php echo $item->primer_apellido ?></td>
            <td><?php echo $item->segundo_apellido ?></td>
            <td><?php echo $item->nie ?></td>
            <td>
                <?php echo Html::linkAction("edit/$item->id/", 'Editar', 'class="btn "') ?>
                <?php echo Html::linkAction("pdf/$item->id", 'Ficha', 'class="btn red"') ?>
                <?php echo Html::linkAction("del/$item->id/", 'Borrar', 'class="btn red"') ?>
            </td>
        </tr>

    <?php endforeach; ?>
</table>