<?php echo View::content() ?>

<h3 class="center-align">Registro de alumnos</h3>
<table>
    <thead>
        <th>ID</th>
        <th>PRIMER NOMBRE</th>
        <th>SEGUNDO NOMBRE</th>
        <th>PRIMER APELLIDO</th>
        <th>SEGUNDO APELLIDO</th>
        <th>FECHA NACIMIENTO</th>
        <th>NACIONALIDAD</th>
        <th>DEPARTAMENTO DE NACIMIENTO</th>
        <th>MUNICIPIO DE NACIMIENTO</th>
        <th>AÑO DE BACHILLERATO</th>
        <th>NIE</th>
        <th>NUMERO DE PARTIDA</th>
        <th>NUMERO DE FOLIO</th>
        <th>LIBRO DE LA PARTIDA</th>
        <th>OTRO DOCUMENTO DE IDENTIFICACION</th>
        <th>SALVADOREÑO POR</th>
        <th>ESPECIALIDAD</th>
        <th>ESTUDIO PARVULARIA</th>
        <th>REPITE GRADO</th>
        <th>CENTRO DE PROCEDENCIA</th>
        <th>AÑO QUE ESTUDIO EL AÑO ANTERIOR</th> -->
    </thead>
    <?php foreach ($listaAlumnos->items as $item): ?>

        <tr>
            <td><?php echo $item->id_alumnos?></td>
            <td><?php echo $item->primer_nombre?></td>
            <td><?php echo $item->segundo_nombre?></td>
            <td><?php echo $item->primer_apellido?></td>
            <td><?php echo $item->segundo_apellido?></td>
            <td><?php echo $item->fecha_nacimiento?></td>
        </tr>
        <?php endforeach;  ?>
</table>
    

