<div class="row">
    <?php View::content() ?>
        <!-- <h3 class="center-align">Ministerio De Educacion</h3> -->
        <h3 class="center-align">Instituto Nacional De Sonzacate</h3>
        <h4 class="center-align">Ficha De Matricula <?php echo date('Y'); ?></h4>
</div>

<div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s3"><a class="active" href="#test1">Identificacion del estudiante</a></li>
        <li class="tab col s3"><a href="#test2">Informacion Del Estudiante</a></li>
        <li class="tab col s3"><a href="#test3">Identificacion Del Responsable</a></li>
        <li class="tab col s3"><a href="#test4">Profesor Que Realizo La Matricula</a></li>
      </ul>
    </div>
</div>
<!-- <div id="test1" class="col s6">Test 1</div>
    <div id="test2" class="col s12">Test 2</div>
    <div id="test3" class="col s12">Test 3</div>
    <div id="test4" class="col s12">Test 4</div> -->


    <!-- IDENTIFICACION DEL ESTUDIANTE -->
    <div id="test1" class="col s6">
        <div class="section">
            <h5>Identificacion del estudiante:</h5>
            <?= Form::open(); ?>
            <?php echo Form::hidden('alumnos.id')?>
            <!-- CAMPOS DE NOMBRES -->
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <label for="Primer_nombre">Primer Nombre:
                    <?= Form::text('alumnos.primer_nombre'); ?></label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <label for="Segundo_nombre">Segundo Nombre:
                    <?= Form::text('alumnos.segundo_nombre'); ?></label>
                </div>
            </div>
        </div>

        <div class="section">
            <!-- CAMPOS DE APELLIDOS -->
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <label for="Primer_apellido">Primer Apellido:
                    <?= Form::text('alumnos.primer_apellido'); ?></label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <label for="Segundo_nombre">Segundo Apellido:
                    <?= Form::text('alumnos.segundo_apellido'); ?></label>
                </div>
            </div>
        </div>


        <div class="section">
            <!-- CAMPOS DE FECHA_NACIMIENTO-->
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">date_range</i>
                    <label for="Fecha_nacimiento">Fecha de nacimiento:
                    <?= Form::date('alumnos.fecha_nacimiento');?></label>
                </div>
                <!-- CAMPOS DE NACIONALIDAD -->
                <div class="input-field col s6">
                    <i class="material-icons prefix">people</i>
                    <label for="Nacionalidad">Nacionalidad:
                    <?php 
                        $arreglo = array('nacionalidades', 'find');
                        echo Form::dbSelect('id_nacionalidad', 'nombre_nacionalidad', $arreglo);?></label>
                </div>
            </div>
        </div>
        <div class="section">
            <!-- CAMPO DEPARTAMENTO DE NACIMIENTO -->
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">assignment_ind</i>
                    <label for="Departamento_nacimiento">Departamento de nacimiento:
                        <?php $ar2 = array('Ahuachapan'=>'Ahuachapan','Sonsonate'=>'Sonsonate','Santa Ana'=>'Santa Ana','Chalatenango'=>'Chalatenango','La Libertad'=>'La Liberta','San Salvador'=>'San Salvador','Cuscatlan'=>'Cuscatlan','Cabañas'=>'Cabañas','La Paz'=>'La Paz','San Vicente'=>'San Vicente','Usulutan'=>'Usulutan','San Miguel'=>'San Miguel','Morazan'=>'Morazan','La Union'=>'La Union');echo Form::Select('departamentos.nombre_departamento', $ar2); ?></label></label>
                </div>
                <!-- CAMPOS DE MUNICIPIO_DE_NACIMIENTO -->
                <div class="input-field col s6">
                    <i class="material-icons prefix">assignment_ind</i>
                    <label for="Municipio_nacimiento">Municipio de nacimiento::
                    <?= Form::text('municipios.nombre_municipio'); ?></label>
                </div>
            </div>
        </div>
        <div class="section">
            <!-- CAMPO AÑO DE BACHILLERATO -->
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">local_library</i>
                    <label for="año_de_bachillerato">Año de bachillerto:
                        <?php $grado = array('1'=>'1°','2'=>'2°','3'=>'3°'); echo Form::Select('alumnos.anio_bachillerato', $grado, NULL); ?></label>
                </div>
                <!-- CAMPOS DE NIE -->
                <div class="input-field col s6">
                    <i class="material-icons prefix">person_pin</i>
                    <label for="Nie">NIE:
                    <?= Form::text('alumnos.nie');?></label>
                </div>       
            </div>
        </div>
        <div class="section">
            <!-- CAMPO DE PARTIDAS DE NACIMIENTO -->
            <div class="row">
                <div class="input-field col s4">
                    <i class="material-icons prefix">perm_identity</i>
                    <label for="Numero_de_partida">Numero de partida de nacimiento:
                    <?= Form::text('alumnos.numero_partida');?></label>
                </div> 
                <div class="input-field col s4">
                    <i class="material-icons prefix">perm_identity</i>
                    <label for="Numero_de_partida">Folio de la partida de nacimiento:
                    <?= Form::text('alumnos.folio_partida');?></label>
                </div>
                <div class="input-field col s4">
                    <i class="material-icons prefix">library_books</i>
                    <label for="Numero_de_partida">libro de la partida de nacimiento:
                    <?= Form::text('alumnos.libro_partida');?></label>
                </div> 
            </div>
        </div>
        <div class="section">
            <!-- CAMPO DE OTRO DOCUMENTO DE IDENTIFICACION -->
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">portrait</i>
                    <label for="Otro_documento_identificacion">Otro documento identificacion:
                    <?= Form::text('alumnos.otro_documento_de_identificacion');?></label>   
                </div>
                <!-- CAMPO DE SALVADOREÑO POR -->
                <div class="input-field col s6">
                    <i class="material-icons prefix">person</i>
                    <label for="Salvadoreño_por">Salvadoreño por:
                    <?= Form::text('alumnos.salvadoreño_por');?></label>   
                </div>
            </div>
        </div>
        <div class="section">
            <!-- CAMPO NOMBRE ESPECIALIDADES -->
            <div class="row">
                <div class="input-field col s4">
                    <i class="material-icons prefix">reorder</i>
                    <label for="especialidad">Especialidad:
                        <?php echo Form::dbSelect('alumnos.id_especialidad_ingreso', 'nombre_especialidad',  array('especialidades', 'find'), 'Seleccione', 'class="form-control"'); ?></label>   
                </div>
                <!-- CAMPO ESTUDIO PARVULARIA -->
                <div class="input-field col s4">
                    <i class="material-icons prefix">account_box</i>
                    <label for="Estudio-parvularia">Estudio parvularia:
                    <?php $parvularia = array('SI'=>'Si','NO'=>'No',''=>'',''=>''); echo Form::Select('alumnos.estudio_parvularia', $parvularia, NULL); ?></label> 
                </div>
                <!-- CAMPO REPITE GRADO -->
                <div class="input-field col s4">
                    <i class="material-icons prefix">account_box</i>
                    <label for="repite_grado">Repite grado:
                    <?php $grado = array('SI'=>'Si','NO'=>'No',''=>'',''=>''); echo Form::Select('alumnos.repite_grado', $grado, NULL); ?></label>
                </div>
            </div>
        </div>
        <div class="section">
            <!-- CAMPO CENTROS ESCOLARES PROVIDENCIAS -->
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_box</i>
                    <label for="Centro_procedencia">Centro de procedencia:
                    <?= Form::text('centros_escolares_providencias.nombre_centroescolar_providencia');?></label>
                </div>

                <!-- CAMPO AÑO ANTERIOR ESTUDIADO -->
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_box</i>
                    <label for="Año_que_estudio_anteriormente">Año que estudio anteriormente:
                    <?= Form::text('alumnos.anio_anterior');?></label>
                </div>
            </div>
        </div>
    </div>


    <!-- INFORMACION DEL ESTUDIANTE -->
    <div id="test2" class="col s12">
        <div class="section">
            <h5>Informacion del estudiante:</h5>
            <!-- CAMPOS TIPO DE SANGRE -->
            <div class="row">
                <div class="input-field col s3">
                    <i class="material-icons prefix">person</i>
                    <label for="Tipo_sangre">Tipo de sangre:
                    <?= Form::text('alumnos.tipo_de_sangre'); ?></label>
                </div>
                <!-- CAMPO SEXO -->
                <div class="input-field col s3">
                    <i class="material-icons prefix">person</i>
                    <label for="Sexo">Sexo:
                        <?php $sexo = array('F'=>'Femenino','M'=>'Masculino'); echo Form::Select('alumnos.sexo', $sexo, NULL); ?></label>
                </div>

                <!-- CAMPO ESTADO_FAMILIAR -->
                <div class="input-field col s3">
                    <i class="material-icons prefix">account_circle</i>
                    <label for="Estado_familiar">Estado Familiar:
                        <?php $estadofamiliar = array('C'=>'Casado','V'=>'Viudo','D'=>'Divorciado','S'=>'Separado','A'=>'Acompañado', 'So'=>'Soltero/a'); echo Form::Select('alumnos.estado_familiar', $estadofamiliar, NULL); ?></label>
                </div>

                <!-- CAMPO DISCAPACIDAD -->
                <div class="input-field col s3">
                    <i class="material-icons prefix">account_box</i>
                    <label for="Discapacidad">Discapacidad:
                    <?php $discapacidad = array('Ninguna'=>'Ninguna','Ceguera'=>'Ceguera','Baja Vision'=>'Baja Vision','Sordera'=>'Sordera','Hipoacusia'=>'Hipoacusia','Sindrome de Down'=>'Sindrome de Down','Retardado Mental'=>'Retardado Mental','Problemas Motores'=>'Problemas Motores','Ausencia de miembros'=>'Ausencia de miembros','Autismo'=>'Autismo',''=>''); echo Form::Select('alumnos.discapacidad', $discapacidad, NULL);?></label>
                </div>
            </div>
        </div>
        <div class="section">
            <h5>Datos de contacto.</h5>

            <!-- CAMPO EMAIL -->
            <div class="row">
                <div class="input-field col s4">
                    <i class="material-icons prefix">mail</i>
                    <label for="Correo_electronico">Correo electronico:
                    <?= Form::text('alumnos.email'); ?></label>
                </div>

                <!-- CAMPO TELEFONO_FIJO -->
                <div class="input-field col s4">
                    <i class="material-icons prefix">call</i>
                    <label for="Telefono_fijo">Tel. Fijo:
                    <?= Form::text('alumnos.telefono_fijo'); ?></label>
                </div>

                <!-- CAMPO CELULAR -->
                <div class="input-field col s4">
                    <i class="material-icons prefix">stay_current_portrait</i>
                    <label for="Celular">Celular:
                    <?= Form::text('alumnos.celular'); ?></label>
                </div>
            </div>
        </div>
        <div class="section">
            <h5>Residencia:</h5>

            <!-- CAMPO ZONA -->
            <div class="row">
                <div class="input-field col s4">
                    <i class="material-icons prefix">list</i>
                    <label for="zona_residencia">Zonas:
                    <?php $zonas = array('Rural'=>'Rural','Urbana'=>'Urbana'); echo Form::Select('zonas.nombre_zona', $zonas, NULL, 'Rural'); ?></label>
                </div>

                <!-- CAMPO DEPARTAMENTO DE RESIDENCIA --> 
                <div class="input-field col s4">
                    <i class="material-icons prefix">assignment_ind</i>
                    <label for="Departamento">Departamento:
                        <?php $ar2 = array('Ahuachapan'=>'Ahuachapan','Sonsonate'=>'Sonsonate','Santa Ana'=>'Santa Ana','Chalatenango'=>'Chalatenango','La Libertad'=>'La Liberta','San Salvador'=>'San Salvador','Cuscatlan'=>'Cuscatlan','Cabañas'=>'Cabañas','La Paz'=>'La Paz','San Vicente'=>'San Vicente','Usulutan'=>'Usulutan','San Miguel'=>'San Miguel','Morazan'=>'Morazan','La Union'=>'La Union',''=>'');echo Form::Select('deparamentos.nombre_departamento', $ar2, NULL, 'Sonsonate'); ?></label>
                </div>

                <!-- CAMPO MUNICIPIO DE RESIDENCIA -->
                <div class="input-field col s4">
                    <i class="material-icons prefix">assignment_ind</i>
                    <label for="Municipio">Municipio:
                    <?= Form::text('municipios.nombre_municipio'); ?></label>
                </div>
            </div>
        </div>
        <div class="section">

            <!-- CAMPO CANTON -->
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">lens</i>
                    <label for="Canton">Cánton:
                    <?= Form::text('cantones.nombre_canton'); ?></label>
                </div>

                <!-- CAMPO CASERIOS -->
                <div class="input-field col s6">
                    <i class="material-icons prefix">lens</i>
                    <label for="Caserio">Caserio:
                    <?= Form::text('caserios.nombre_caserio'); ?></label>
                </div>
            </div>
        </div>
        <div class="section">

            <!-- CAMPO TIPOS DE CALLE -->
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">chevron_right</i>
                    <label for="Canton">Tipo de calle:
                    <?= Form::text('alumnos.tipo_de_calle'); ?></label>
                </div>
                <!-- CAMPO DIRECCION_COMPLETA -->
                <div class="input-field col s6">
                    <i class="material-icons prefix">directions_walk</i>
                    <label for="Caserio">Dirección completa del estudiante:
                    <?= Form::text('alumnos.direccion_completa'); ?></label>
                </div>
            </div>
        </div>
        <div class="section">
            <h5>Otros Datos.</h5>

            <!-- CAMPO MEDIO_TRANSPORTE -->
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">directions_bus</i>
                    <label for="Medio_de_transpote">Medio de transporte para llegar al centro educativo:
                    <?php $transporte = array('A pie'=>'A pie','Bicicleta'=>'Bicicleta','Autobus'=>'Autobus','Vehiculo propio'=>'Vehiculo propio','Otro'=>'Otro',''=>''); echo Form::Select('alumnos.medio_de_transporte', $transporte, NULL); ?></label>
                </div>

                <!-- CAMPO DISTANICIA ENTRE EL INSO Y TU CASA -->
                <div class="input-field col s6">
                    <i class="material-icons prefix">compare_arrows</i>
                    <label for="Distancia">kilometros de distacia entre el instituto y su residencia:
                    <?= Form::text('alumnos.distancia_desde_casa_y_centroeducativo'); ?></label>
                </div>
            </div>
        </div>
        <div class="section">

            <!-- FACTOR DE RIESGO -->
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">add_alert</i>
                    <label for="Factor_de_riesgo">Factor de riesgo:
                    <?= Form::text('alumnos.factor_de_riesgo'); ?></label>
                </div>
            </div>
        </div>
        <div class="section">
            <h5>Grupo familiar:</h5>

            <!-- CAMPO NUMERO DE INTEGRANTES FAMILIA -->
            <div class="row">
                <div class="input-field col s4">
                    <i class="material-icons prefix">wc</i>
                    <label for="Numero_integrantes_familia">Numero de integrantes de la familia:
                    <?= Form::text('alumnos.numero_integrantes_familia'); ?></label>
                </div>

                <!-- CAMPO INTEGRADOS -->
                <div class="input-field col s4">
                    <i class="material-icons prefix">wc</i>
                    <label for="Integrados">Integrados:
                    <?= Form::text('alumnos.integrados'); ?></label>
                </div>

                <!-- CAMPO DEPENDE ECONOMICAMENTE DE -->
                <div class="input-field col s4">
                    <i class="material-icons prefix">attach_money</i>
                    <label for="Depende_economicamente">Depende economicamente de:
                    <?= Form::text('alumnos.depende_economicamente_de'); ?></label>
                </div>
            </div>
        </div>
        <div class="section">

            <!-- CAMPO TIENE HIJOS -->
            <div class="row">
                <div class="input-field col s3">
                    <i class="material-icons prefix">group</i>
                    <label for="Tiene_hijos">Tiene hijos:
                    <?= Form::text('alumnos.tiene_hijos'); ?></label>
                </div>
                <div class="input-field col s3">
                    <i class="material-icons prefix">group</i>
                    <label for="Cuantos_tiene_hijos">Cuantos hijos tiene:
                    <?= Form::text('alumnos.numero_de_hijos'); ?></label>
                </div>
                <div class="input-field col s3">
                    <i class="material-icons prefix">build</i>
                    <label for="Trabaja">Trabaja:
                    <?= Form::text('alumnos.trabaja'); ?></label>
                </div>
                <div class="input-field col s3">
                    <i class="material-icons prefix">wc</i>
                    <label for="Convivenicia_con">Convivencia con:
                    <?= Form::text('alumnos.convivencia_con'); ?></label>
                </div>
            </div>
        </div>
        <div class="section">
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <label for="Nombre_de_la_madre">Nombre de la madre:
                    <?= Form::text('alumnos.nombre_madre'); ?></label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">assignment_turned_in</i>
                    <label for="Nombre_de_la_madre">Ocupación:
                    <?= Form::text('alumnos.ocupacion_padre'); ?></label>
                </div>
            </div>
        </div>
        <div class="section">
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">accessibility</i>
                    <label for="Lugar_de_trabajo-madre">Lugar de trabajo (madre):
                    <?= Form::text('alumnos.lugar_de_trabajo_madre'); ?></label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">call</i>
                    <label for="telefono-madre">Telefono (madre):
                    <?= Form::text('alumnos.telefono_madre'); ?></label>
                </div>
            </div>
        </div>
        <div class="section">
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <label for="Nombre_del_padre">Nombre del padre:
                    <?= Form::text('alumnos.nombre_padre'); ?></label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">assignment_turned_in</i>
                    <label for="Ocupacion_del_padre">Ocupación:
                    <?= Form::text('alumnos.ocupacion_padre'); ?></label>
                </div>
            </div>
        </div>
        <div class="section">
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">accessibility</i>
                    <label for="Lugar_de_trabajo">Lugar de trabajo (padre):
                    <?= Form::text('alumnos.lugar_de_trabajo_padre'); ?></label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">call</i>
                    <label for="telefono-padre">Telefono (padre):
                    <?= Form::text('alumnos.telefono_padre'); ?></label>
                </div>
            </div>
        </div>
    </div>


    <!-- IDENTIFICACION DEL RESPONSABLE -->
    <div id="test3" class="col s12">
        <div class="section">
            <h5>Identificacion Del Responsable:</h5>
            <!-- CAMPOS DE NOMBRES ENCARGADOS -->
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <label for="Primer_nombre_encargado">Primer Nombre:
                    <?= Form::text('alumnos.primer_nombre_responsable'); ?></label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <label for="segundo-nombre-responsabe">Segundo Nombre:
                    <?= Form::text('alumnos.segundo_nombre_responsable'); ?></label>
                </div>
            </div>
        </div>
        <div class="section">
            <!-- CAMPOS DE APELLIDOS ENCARGADOS -->
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <label for="Primer_apellido_encargado">Primer Apellido:
                    <?= Form::text('alumnos.primer_apellido_reponsable'); ?></label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <label for="Segundo_nombre_encargado">Segundo Apellido:
                    <?= Form::text('alumnos.segundo_apellido_responsable'); ?></label>
                </div>
            </div>
        </div>
        <div class="section">
            <!-- CAMPOS DE DUI Y ESTADO FAMILIAR -->
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <label for="numero-dui-responsable">Numero de DUI:
                    <?= Form::text('alumnos.numero_dui_responsable'); ?></label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">account_circle</i>
                    <label for="Estado_familiar_responsable">Estado Familiar:
                        <?php $estadofamiliarresponsable = array('S'=>'Soltero','C'=>'Casado','V'=>'Viudo','D'=>'Divorciado','S'=>'Separado','A'=>'Acompañado',''=>''); echo Form::Select('alumnos.estado_familiar_responsable', $estadofamiliarresponsable, NULL); ?></label>
                </div>
            </div>
        </div>
        <div class="section">
            <h5>Datos de contacto.</h5>
            <!-- DATOS DE CONTACTO DEL ENCARGADO -->
            <div class="row">
                <div class="input-field col s4">
                    <i class="material-icons prefix">mail</i>
                    <label for="Correo_electronico_encargado">Correo electronico:
                    <?= Form::text('alumnos.email_responsable'); ?></label>
                </div>
                <div class="input-field col s4">
                    <i class="material-icons prefix">call</i>
                    <label for="Telefono_fijo_encargado">Tel. Fijo:
                    <?= Form::text('alumnos.telefono_fijo_encargado'); ?></label>
                </div>
                <div class="input-field col s4">
                    <i class="material-icons prefix">stay_current_portrait</i>
                    <label for="Telefono_fijo_encargado">Celular:
                    <?= Form::text('alumnos.celular_encargado'); ?></label>
                </div>
            </div>
        </div>

        <!-- RESIDENCIA DEL ENCARGADO -->
        <div class="section">
            <h5>Residencia:</h5>
            <div class="row">
                <div class="input-field col s4">
                    <i class="material-icons prefix">list</i>
                    <label for="zona_residencia">Zonas:
                    <?php $zonas_responsable = array('Rural'=>'Rural','Urbana'=>'Urbana',''=>''); echo Form::Select('zonas.nombre_zona', $zonas_responsable, NULL, 'Rural'); ?></label>
                </div>
                <div class="input-field col s4">
                    <i class="material-icons prefix">assignment_ind</i>
                    <label for="Departamento-responsable">Departamento:
                        <?php $ar2 = array('Ahuachapan'=>'Ahuachapan','Sonsonate'=>'Sonsonate','Santa Ana'=>'Santa Ana','Chalatenango'=>'Chalatenango','La Libertad'=>'La Liberta','San Salvador'=>'San Salvador','Cuscatlan'=>'Cuscatlan','Cabañas'=>'Cabañas','La Paz'=>'La Paz','San Vicente'=>'San Vicente','Usulutan'=>'Usulutan','San Miguel'=>'San Miguel','Morazan'=>'Morazan','La Union'=>'La Union',''=>'');echo Form::Select('deparamentos.nombre_departamento', $ar2, NULL, 'Sonsonate'); ?></label>
                </div>
                <div class="input-field col s4">
                    <i class="material-icons prefix">assignment_ind</i>
                    <label for="Municipio_encargado">Municipio:
                    <?= Form::text('municipios.nombre_municipio'); ?></label>
                </div>
            </div>
        </div>

        <!-- CANTON, CASERIO DEL ENCARGADO -->
        <div class="section">
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">lens</i>
                    <label for="Canton_encargado">Cánton:
                    <?= Form::text('cantones.nombre_canton'); ?></label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">lens</i>
                    <label for="Caserio_encargado">Caserio:
                    <?= Form::text('caserios.nombre_caserio'); ?></label>
                </div>
            </div>
        </div>
        <div class="section">
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">chevron_right</i>
                    <label for="tipo_de_calle_encargado">Tipo de calle:
                    <?= Form::text('alumnos.tipo_de_calle_responsable'); ?></label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">directions_walk</i>
                    <label for="direccion_encargado">Dirección completa del encargado:
                    <?= Form::text('alumnos.direccion_completa_responsable'); ?></label>
                </div>
            </div>
        </div>

        <!-- OTROS DATOS DEL RESPONSABLE -->
        <div class="section">
            <h5>Otros datos del responsable:</h5>
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">build</i>
                    <label for="profesion_encargado">Profesion u oficio (padre):
                    <?= Form::text('alumnos.profesion_oficio_responsable'); ?></label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">call</i>
                    <label for="profesion_encargado">Telefono o celular:
                    <?= Form::text('alumnos.celular_responsable'); ?></label>
                </div>
            </div>
        </div>
        <div class="section">
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">border_color</i>
                    <label for="Escolaridad_encargado">Escolaridad:
                    <?= Form::text('alumnos.escolaridad_responsable'); ?></label>
                </div>
                <div class="input-field col s6">
                    <i class="material-icons prefix">add_alert</i>
                    <label for="Factor-de-riesgo">Factor de riesgo:
                    <?= Form::text('alumnos.factor_de_riesgo_responsable'); ?></label>
                </div>
            </div>
        </div>
    </div>


    <!-- RESERVADO PARA EL PROFESOR -->
    <div id="test4" class="col s12">
        <div class="section">
            <h5>Reservado para el profesor que realizo la Matricula:</h5>
            <div class="row">
                <div class="input-field col s6">
                    <i class="material-icons prefix">insert_invitation</i>
                    <label for="Fecha_revision_formulario">Fecha en que fue revisado este formulario:
                    <?= Form::date('alumnos.fecha_revision_formulario'); ?></label>
                </div>
            </div>
        </div>
        
        <div class="section">
            <div class="row">
                <div class="input-field col s12">
                    <button class="btn waves-effect waves-light" type="submit" name="action">Enviar
                    <i class="material-icons right">send</i>
                </button>
                </div>
            </div>
            <?= Form::close(); ?>
        </div>
    </div>      