<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title><?php echo $titulo ?></title>
</head>

<body>
    
    <nav class="teal lighten-2">
        <div class="nav-wrapper container">
            <ul class="right hide-on-med-and-down">
                <li><?php echo Html::Link('alumnos', 'Alumnos') ?></li>
                <li><?php echo Html::Link('alumnos/registros','Registro de alumnos') ?></li>
                <li><?php echo Html::Link('matricula','Matriculas') ?></li>
                <li><?php echo Html::Link('profesores/create','Formulario Profesores') ?></li>
                <li><?php echo Html::Link('profesores','Profesores') ?></li>
                <li><?php echo Html::Link('nacionalidades', 'Nacionalidades') ?></li>
                <li><?php echo Html::Link('nacionalidades/create', 'Form Nacionalidades') ?></li>
                <li><?php echo Html::Link('departamentos', 'Departamentos') ?></li>
                <li><?php echo Html::Link('nacionalidades', 'Nacionalidades')?></li>
            </ul>
        </div>
    </nav>


    <div class="container">
        <?php View::content() ?>
    </div>

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('.tabs').tabs();
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('select').formSelect();
        });
    </script>


</body>

</html>