<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title><?php echo $titulo ?></title>
</head>
<body>

    <div class="container">
        <?php View::content() ?>
    </div>

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <!-- <--Compiled and minified JavaScript -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> 

     <script type="text/javascript">
        function arrayjsonbarcode(j){
        json = JSON.parse(j);
        arreglo = [];
        for (let x in json) {
            arreglo.push(json[x]);
        }

        return arreglo;
    }

    jsonvalor = '<?php echo json_encode($arraycodigos)?>';
    valores = arrayjsonbarcode(jsonvalor);

    for (let i = 0; i < valores.length; i++) {
        JsBarcode("#barcode" + valores[i], valores[i].toString(),{
            format: "CODE128",
            ean128: true,
            lineColor: "#000",
            width: 2,
            height: 95,
            displayValue: true
        })
    }
    </script>
</body>
</html>