<div class="row section">
<?php echo View::content(); ?>
 <h3 class="center"><b>Municipios</b></h3>

   <?php echo Form::open(); ?>
  <div class="col s6">
     <label for="">Ingrese el Municipio
          <?php echo Form::text('municipios.nombre_municipio'); ?>

      </label>
 </div>
 <div class="col s6">
     <label for="habilitado">
         Habilitado
         <?php 
         $arreglo = array('Habilitado', 'Inhabilitado');
         echo Form::select('municipios.habilitado', $arreglo);
         ?>
     </label>
 </div>
     <div class="col s12">
         <?php echo Form::submit('Guardar', 'class="btn teal accent-3"')?>
         <?php echo Form::reset('Limpiar', 'class="btn light-blue darken-"')?>
         <?php echo Html::linkAction('index', 'regresar', "class='btn blue lighten-2'") ?>
     </div>
     
     <?php echo Form::close(); ?>

</div>