<?php echo View::content() ?>
<h4 class="center-align">MUNICIPIOS</h4>
  
<?php echo Html::linkAction('create','Agregar municipio +', "class='btn green accent-4'") ?>

<br>
<hr>

<table class="responsive-table centered table striped">
    <thead class="blue lighten-4">
        <th>ID</th>
        <th>NOMBRE MUNICIPIO</th>
        <th>ACTIVO</th>
        <th>ACCIONES</th>
    </thead>

      <?php foreach($ListaMunicipios->items as $item): ?>
          <tr>
              <td><?php echo $item->id ?></td>
              <td><?php echo $item->nombre_municipio ?></td>
              
              <td>
                  <?php 
                   if ($item->habilitado==1) {
                       echo "Habilitado";
                   }
                   if ($item->habilitado ==0) {
                       echo "Inhabilitado";
                   }
                  ?>

              </td>

              <div class= "botones">
                 <td>
                       <?php echo Html::linkAction("edit/$item->id/", "Editar", 'class="btn blue darken-3"') ?>
                       <?php echo Html::linkAction("del/$item->id/", "Eliminar", 'class="btn red"') ?>
                 </td>
            </div> 
          </tr>
       <?php endforeach ?>  
    </tr>
</table>   