<?php echo View::content() ?>
<h3 clas="center"><b>Municipios</b></h3>
<table class="centered">  
    <tr>
      <thead>
          <th>Id</th>
          <th>Municipios</th>
      </thead>

      <?php foreach($ListaMunicipios->items as $item): ?>
          <tr>
              <td><?php echo $item->id ?></td>
              <td><?php echo $item->municipio ?></td>
              <td>
                <?php echo Html::linkAction("edit/$item->id/", "Editar", 'class="btn"') ?>
                <?php echo Html::linkAction("del/$item->id/", "Eliminar", 'class="btn red"') ?>
              </td>
          </tr>
       <?php endforeach ?>  
    </tr>
</table>   