<?php echo View::content() ?>
<h3 class="center"><b>Registro de matriculas</b></h3>

<table class="centered">
    <tr>
        <thead class="blue">
            <th>Id</th>
            <th>Alumno</th>
            <th>Especialidad</th>
            <th>Seccion</th>
            <th>Año</th>
            <th>Estado</th>
            <th>Egresado</th>
            <th>Acciones</th>
        </thead>

        <?php foreach ($ListaMatriculas->items as $item) :  ?>
    <tr>
        <td><?php echo $item->id ?></td>
        <td><?php $alumnos = Load::model('alumnos')->find_all_by_sql("select primer_nombre, segundo_nombre,	primer_apellido,	segundo_apellido	from matricula, alumnos where alumnos.id=matricula.id_alumno") ?></td>
        <td><?php $alumnos = Load::model('alumnos')->find_all_by_sql("select nombre_especialidad	from matricula, especialidades where alumnos.id=matricula.id_especialidad") ?></td>
        <td><?php $alumnos = Load::model('alumnos')->find_all_by_sql("select anio_bachillerato	from matricula, especialidades where alumnos.id=matricula.id_seccion") ?></td>
        <td><?php echo $item->anio ?></td>
        <td><?php echo $item->estado ?></td>
        <td><?php echo $item->egresado ?></td>
        <td>
            <?php echo Html::linkAction("edit/$item->id/", "Editar", 'class="btn"') ?>
            <?php echo Html::linkAction("del/$item->id/", "Borrar", 'class="btn red"') ?>
        </td>
    </tr>
    </tr>
<?php endforeach;  ?>
</tr>
</table>