<div class="row">
    <?php View::content(); ?>
    <h3>Caserios</h3>
    <?= Form::open(); ?>
        <div class="row">
            <div class="col s6">
                <label for="Nombre_caserio">
                <?= Form::text('caserios.nombre_caserio'); ?></label>
            </div>
        </div>
        <div class="col s12">
            <?= Form::submit('Guardar',"class='btn teal'"); ?>
        </div>
    <?= Form::close(); ?>
</div>