<div class="row">
    <?php View::content(); ?>
    <h3 class="center">Caserios</h3>
    <?php echo Form::open(); ?>
        <div class="row">
            <div class="col s6">
                <label for="">nombre del caserio
                <?php echo Form::text('caserios.nombre_caserio'); ?></label>
            </div>
            <div class="col s6">
                <label for="habilitado">Habilitado
                    <?php 
                    $arreglo = array('Inhabilitado','Habilitado');
                    echo Form::select('caserios.habilitado', $arreglo);
                    ?>
                </label>
            </div>
        </div>
        <div class="col s12">
            <?php echo Form::submit('Guardar',"class='btn teal'"); ?>
            <?php echo Html::linkAction('index', 'regresar', "class='btn green'") ?>
        </div>
    <?php echo Form::close(); ?>
</div>
