<div class="row">
    <?php echo View::content(); ?>
    <?php echo Form::open(); ?>
        <div class="col s6">
            <label>
             <?php echo Form::text('caserios.nombre_caserio'); ?>
            </label>
        </div>
        <div class="col s6">
            <label>
                <input type="checkbox"/>
                <?php echo Form::check('caserios.habilitado','1','',true); ?>
                <span>Habilitado</span>
            </label>
        </div>
        <div class="col s12">
            <?php echo Form::hidden('caserios.id'); ?>
            <?php echo Form::submit('guardar','class="btn green"') ?>
        </div>
        <?php echo Form::close(); ?>
</div>