<?php echo View::content(); ?>
<h3 class="centered">caserios</h3>
<?php echo Html::linkAction('create','Nuevo Caserio',"class='btn green right'") ?>

<table class="centered table striped">
    <tr>
        <thead class="blue lighten-3">
            <th>Id</th>
            <th>Caserio</th>
            <th>activo</th>
            <th>Acciones</th>
        </thead>
        <?php foreach($listaCaserios->items as $item): ?>
            <tr>
                <td><?php echo $item->id?></td>
                <td><?php echo $item->nombre_caserio?></td>
                <td>
                    <?php 
                    if ($item->habilitado ==1){
                        echo "Habilitado";
                    }
                    if ($item->habilitado == 0){
                        echo "Inhabilitado";
                    }
                    ?>
                <td>
                    <?php echo Html::LinkAction("edit/$item->id",'editar','class="btn"') ?>
                    <?php echo Html::LinkAction("del/$item->id",'borrar','class="btn red"') ?>
                </td>
            </tr>
        <?php endforeach ?>   
    </tr>
</table>
        