<?php echo View::content(); ?>
<h3>caserios</h3>
<table>
    <thead>
         <th>id</th>
         <th>nombre_caserio</th>
    </thead>
    <?php foreach($listaCaserios->items as $item): ?>
        <tr>
            <td><?php echo $item->id_caserio?></td>
            <td><?php echo $item->nombre_caserio?></td>
            <td>
                <?php echo Html::LinkAction("edit/$item->id",'editar','class="btn"') ?>
                <?php echo Html::LinkAction("del/$item->id",'borrar','class="btn red"') ?>
             </td>
        </tr>
     <?php endforeach; ?>   
</table>
        