<?php echo View::content(); ?>
<h4 class="center-align">CASERIOS</h3>
<?php echo Html::linkAction('create','Nuevo Caserio',"class='btn green accent-4'") ?>

<br>
<hr>

<table class="responsive-table centered table striped">
    <tr>
        <thead class="blue lighten-4">
            <th>ID</th>
            <th>CASERIO</th>
            <th>ACTIVO</th>
            <th>ACCIONES</th>
        </thead>
        <?php foreach($listaCaserios->items as $item): ?>
            <tr>
                <td><?php echo $item->id?></td>
                <td><?php echo $item->nombre_caserio?></td>
                <td>
                    <?php 
                    if ($item->habilitado ==1){
                        echo "Habilitado";
                    }
                    if ($item->habilitado == 0){
                        echo "Inhabilitado";
                    }
                    ?>
                <td>
                    <?php echo Html::LinkAction("edit/$item->id",'editar','class="btn blue darken-3"') ?>
                    <?php echo Html::LinkAction("del/$item->id",'borrar','class="btn red"') ?>
                </td>
            </tr>
        <?php endforeach ?>   
    </tr>
</table>
        