    <?php echo View::content(); ?>
        <h3 class="center">LISTADO DE ESPECIALIDADES</h3>
    <table class="table striped">
        <thead>
            <th>id</th>
            <th>Nombre Especialidad</th>
            <th>Activo</th>
            <th>Acciones</th>
        </thead>
        <?php foreach($listaEspecialidades->items as $item) :?>
            <tr>
                <td><?php echo $item->id ?></td>
                <td><?php echo $item->nombre_especialidad ?></td>
                <td>
                    <?php 
                        if ($item->habilitado == 1) {
                            echo "Habilitado";
                        }
                        if ($item->habilitado == 0) {
                            echo "Inhabilitado";
                        }
                    ?>
                </td>
                <td>
                    <?php echo Html::linkAction('edit/'.$item->id,'Editar',"class='btn info'")  ?>
                    <?php echo Html::linkAction('del/'.$item->id,'Eliminar', "class='btn red'") ?><br/>
                </td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <td><?php echo Html::linkAction('create','Nueva Especialidad', "class='btn green'") ?></td>
        </tr>
    </table>
    <?php if($listaEspecialidades->prev) echo Html::linkAction("index/$listaEspecialidades->prev", '<< Anterior|') ?>
    <?php if($listaEspecialidades->next) echo Html::linkAction("index/$listaEspecialidades->next/", 'Próximo >>') ?>
</div>