<div class="row">
    <?php echo View::content(); ?>
        <h3>LISTADO DE ESPECIALIDADES</h3>
    <table class="table striped">
        <thead>
            <th>id</th>
            <th>Nombre Especialidad</th>
            <th>Activo</th>
        </thead>
        <?php foreach($listaEspecialidades->items as $item) :?>
            <tr>
                <td><?php echo $item->id ?></td>
                <td><?php echo $item->nombre_especialidad ?></td>
                <td>
                    <!-- Switch -->
                    <div class="switch">
                        <label>
                        Off
                        <input type="checkbox">
                        <span class="lever"></span>
                        On
                        </label>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>