<?php echo View::content(); ?>
<h4 class="center-align">LISTADO DE ESPECIALIDADES</h4>

<?php echo Html::linkAction('create','Nueva Especialidad +', "class='btn green accent-4'") ?>

<br>
<hr>

    <table class="responsive-table centered table striped">
        <thead class="blue lighten-4">
            <th>ID</th>
            <th>NOMBRE ESPECIALIDAD</th>
            <th>ATIVO</th>
            <th>ACCIONES</th>
        </thead>
        <?php foreach($listaEspecialidades->items as $item) :?>
            <tr>
                <td><?php echo $item->id ?></td>
                <td><?php echo $item->nombre_especialidad ?></td>
                <td>
                    <?php 
                        if ($item->habilitado == 1) {
                            echo "Habilitado";
                        }
                        if ($item->habilitado == 0) {
                            echo "Inhabilitado";
                        }
                    ?>
                </td>
                <td>
                    <?php echo Html::linkAction('edit/'.$item->id,'Editar',"class='btn blue darken-3'")  ?>
                    <?php echo Html::linkAction('del/'.$item->id,'Eliminar', "class='btn red'") ?><br/>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <?php if($listaEspecialidades->prev) echo Html::linkAction("index/$listaEspecialidades->prev", '<< Anterior|') ?>
    <?php if($listaEspecialidades->next) echo Html::linkAction("index/$listaEspecialidades->next/", 'Próximo >>') ?>