<div class="row section">
    <?php View::content(); ?>
    <h3>zonas</h3>
    <?php echo Form::open(); ?>
        <div class="row">
            <div class="col s6">
                <label for="">
                <?php echo Form::text('zonas.nombre_zona'); ?></label>
            </div>
            <div class="col s6">
                <label for="">
                <input type="checkbox">
                <?php echo Form::check('zonas.habilitado','1','',true); ?>
                <span>Habilitado</span>
                </label>
            </div>
        </div>
        <div class="col s12">
            <?php echo Form::submit('Guardar',"class='btn teal'"); ?>
        </div>
    <?= Form::close(); ?>
</div>