<div class="row section">
    <?php View::content(); ?>
    <h3>zonas</h3>
    <?php echo Form::open(); ?>

        <div class="col s6">
            <label for="">Ingrese la zona
            <?php echo Form::text('zonas.nombre_zona'); ?></label>
        </div>

        <div class="col s12">
            <?php echo Form::submit('Guardar',"class='btn teal'"); ?>
        </div>
    <?php echo Form::close(); ?>
</div>
