<div class="row section">
    <?php View::content(); ?>
    <h3 class="center">zonas</h3>
    <?php echo Form::open(); ?>
        <div class="row">
            <div class="col s6">
                <label for="">nombre de la zona
                <?php echo Form::text('zonas.nombre_zona'); ?></label>
            </div>

            <div class="col s6">
                <label for="habilitado">Habilitado
                <?php 
                $arreglo = array('Inhabilitado','Habilitado');
                echo Form::select('zonas.habilitado', $arreglo);
                 ?>
            
                </label>
            </div>
        </div>
        <div class="col s12">
            <?php echo Form::submit('Guardar',"class='btn teal'"); ?>
        </div>
    <?= Form::close(); ?>
</div>