<div class="row">
    <?php echo View::content();?>
    <?php echo Form::open(); ?>
        <div class="col s6">
            <label>
            <?php echo Form::text('zonas.nombre_zona');?></label>
        </div>
        <div class="col s6">
            <label>
            <?php echo Form::text('zonas.habilitado');?></label>
        </div>
        <div class="col s12">
            <?php echo Form::hidden('zonas.nombre_zona');?>
            <?php echo Form::hidden('zonas.habilitado');?>
            <?php echo Form::submit('guardar','class="btn green"') ?>
        </div>
    <?php echo Form::close(); ?>
</div> 