<?php echo View::content(); ?>
<div class="center">
    <h3 class=" card panel light-blue darken-4">zonas</h3>
</div>
<table>
    <tr>
        <thead class="blue lighten-3">
            <th>Id</th>
            <th>Zona</th>
            <th>Habilitado</th>
            <th>Acciones</th>
        </thead>

        <?php foreach ($listaZonas->items as $item): ?>
            <tr>
                <td><?php echo $item->id?></td>
                <td><?php echo $item->nombre_zona ?></td>
                <td><?php echo $item->habilitado ?></td>
                <td>
                    <?php echo Html::LinkAction("edit/$item->id_zona", "Editar", 'class="btn"') ?>
                    <?php echo Html::LinkAction("del/$item->id_zona", "Borrar", 'class="btn red"') ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tr>
</table>