<?php echo View::content(); ?>
<div class="center">
    <h3 class="centered">zonas</h3>
</div>
<table class="centered table striped">
    <tr>
        <thead class="blue lighten-3">
            <th>Id</th>
            <th>Zona</th>
            <th>Acciones</th>
        </thead>
        <?php foreach ($listaZonas->items as $item): ?>
            <tr>
                <td><?php echo $item->id?></td>
                <td><?php echo $item->nombre_zona ?></td>
                <td>
                    <?php echo Html::LinkAction("edit/$item->id", "Editar", 'class="btn"') ?>
                    <?php echo Html::LinkAction("del/$item->id", "Borrar", 'class="btn red"') ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tr>
    <tr>
     <td><?php echo Html::linkAction('create','Nueva Zona',"class='btn green'") ?></td>
    </tr>
</table>