<?php echo View::content(); ?>
    <h4 class="center-align">ZONAS</h4>

     <?php echo Html::linkAction('create','Nueva Zona +',"class='btn green accent-4'") ?>

     <br>
     <hr>
    
<table class="responsive-table centered table striped">
    <tr>
        <thead class="blue lighten-4">
            <th>id</th>
            <th>NOMBRE ZONA</th>
            <th>ACTIVO</th>
            <th>ACCIONES</th>
        </thead>
        <?php foreach ($listaZonas->items as $item): ?>
            <tr>
                <td><?php echo $item->id?></td>
                <td><?php echo $item->nombre_zona ?></td>
                <td>
                    <?php 
                    if ($item->habilitado ==1){
                        echo "Habilitado";
                    }
                    if ($item->habilitado == 0){
                        echo "Inhabilitado";
                    }
                    ?>
                </td>
                <td>
                    <?php echo Html::LinkAction("edit/$item->id", "Editar", 'class="btn blue darken-3"') ?>
                    <?php echo Html::LinkAction("del/$item->id", "Borrar", 'class="btn red"') ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tr>
</table>