<div class="container">
    <div class="row">
        <?php View::content() ?>
        <h3 class="center-align">Creando Cargo De Profesores</h3>
        <h4 class="center-align">(I.N.S.O)</h4>
    </div>
</div>

<?php echo Form::open(); ?>

<div class="container">
    <div class="section">
        <div class="row">
            <!-- NOMBRE CATEGORIA -->
            <div class="input-field col s12">
                <i class="material-icons prefix">account_circle</i>
                <label for="Cargo">Cargo:
                    <?= Form::text('cargos.nombre_cargo'); ?></label>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="row">
            <!-- HABILITADO -->
            <div class="input-field col s12">
                <i class="material-icons prefix">content_copy</i>
                <label for="habilitado">Habilitado:</label><br>
                    <?php
                    $arreglo = array('Inhabilitado', 'Habilitado');
                    echo Form::select('cargos.habilitado', $arreglo);
                    ?>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="row">
            <div class="input-field col s12 center-align">
                <button class="btn waves-effect waves-light " type="submit" name="action">Crear
                <i class="material-icons right">send</i>
                </button>
                <?php echo Html::linkAction('index', 'regresar', "class='btn green darken-1'") ?>
            </div> 
        </div>
    </div>
</div>

<?php echo Form::close(); ?>