<div class="container">
    <div class="row">
        <?php View::content() ?>
        <h3 class="center-align">Creando Cargo De Profesores</h3>
    </div>
</div>

<?php echo Form::open(); ?>

<div class="container">
    <div class="section">
        <div class="row">
            <!-- NOMBRE CATEGORIA -->
            <div class="input-field col s12">
                <i class="material-icons prefix">account_circle</i>
                <label for="Cargo">Cargo:
                    <?= Form::text('cargos.nombre_cargo'); ?></label>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="row">
            <!-- HABILITADO -->
            <div class="input-field col s12">
                <i class="material-icons prefix">content_copy</i>
                <label for="habilitado">Habilitado:</label><br>
                    <?php
                    $arreglo = array('Inhabilitado', 'Habilitado');
                    echo Form::select('cargos.habilitado', $arreglo);
                    ?>
            </div>
        </div>
    </div>

    <div class="section">
        <div class="row">
            <div class="input-field col s12 center-align">
            <?php echo Form::hidden('cargos.id'); ?>
            <?php echo Form::submit('Actualizar',"class='btn green'"); ?>
            </div> 
        </div>
    </div>
</div>

<?php echo Form::close(); ?>