<?php echo View::content() ?>

<h3 class="center">
    Cargo de profesores
</h3>
<?php echo Html::linkAction("create", 'Agregar Cargo +', "class='btn'") ?>

<table class="responsive-table centered table striped">
    <thead class="light-blue lighten-1">
        <th>ID</th>
        <th>NOMBRE CARGO</th>
        <th>HABILITADO</th>
        <th>ACCIONES</th>
    </thead>
    <?php foreach($listaCargos->items as $item) :?>
            <tr>
                <td><?php echo $item->id ?></td>
                <td><?php echo $item->nombre_cargo ?></td>
                <td>
                    <?php 
                        if ($item->habilitado == 1) {
                            echo "Habilitado";
                        }
                        if ($item->habilitado == 0) {
                            echo "Inhabilitado";
                        }
                    ?>
                </td>
                <td>
                    <?php echo Html::linkAction('edit/'.$item->id,'Editar',"class='btn info'")  ?>
                    <?php echo Html::linkAction('del/'.$item->id,'Eliminar', "class='btn red'") ?><br/>
                </td>
            </tr>
        <?php endforeach; ?>
</table>
        
<?php if($listaCargos->prev) echo Html::linkAction("index/$listaCargos->prev", '<< Anterior|') ?>
<?php if($listaCargos->next) echo Html::linkAction("index/$listaCargos->next/", 'Próximo >>') ?>